### ISSUE TITLE
Not initialized on android when in Shipping mode

### ISSUE THREAD

**Issue by HereafterMills** [AgoraIO-Extensions/Agora-Unreal-RTC-SDK#100]
Hey. Is there any reason why when i upload to android store, it works when in a development apk pushed via adb. The only difference i can see is that store is built with target 33 and apk was targeting 32

**Comment by WinterPu** [comment]
Sorry, I don't get it. Do you mean it doesn't work? Please provide more detailed information or logs.

**Comment by HereafterMills** [comment]
Ok, heres what i did. 

**Built for Android 33 - directly to go on the store - distribution - No logs since its shipping**
This didnt work. For some reason, the init function itself fails or is never hit. Im checking the blueprint to ensure its not an issue with my own setup, but dont think it is since its working otherwise. This never asked for any permissions. 

**Built for android 32 - APK - installed via ADB**
Works! But never asked for permission. I had to go into app info to enable permissions.

**Built for android 33 - APK - installed via ADB**
Works! And asked for permissions as well. 

Can you make sense of this? Cause the only common point here i can think of is the Play Store.

**Comment by HereafterMills** [comment]
@WinterPu 
So i did some more testing. Voice doesnt work specifically when in shipping mode. All i can get for this is logcat logs. 
[phoneLogs.log](https://github.com/AgoraIO-Extensions/Agora-Unreal-RTC-SDK/files/13254929/phoneLogs.log)
The app is called ToolboxVR (for searching through it)

When i say it doesnt work, i dont believe that even the initialization is happening because i have a callback connected to show me if theres any change in the connection state even in shipping. 

This is what my blueprints look like. 

PlayerController calls init and then join channel on the game instance:
![image](https://github.com/AgoraIO-Extensions/Agora-Unreal-RTC-SDK/assets/37168482/261756e3-7456-4da4-969b-6c0f600a09ca)

This is the init function: 
![image](https://github.com/AgoraIO-Extensions/Agora-Unreal-RTC-SDK/assets/37168482/aa837dc1-b466-4399-897b-c8b1732724aa)

This is the join function:
![image](https://github.com/AgoraIO-Extensions/Agora-Unreal-RTC-SDK/assets/37168482/9e36fa95-0600-4689-9a7c-0693bb92f636)
Ignore the aws lambda stuff, thats simply to get a token to connect. 


Some help on this would be great. Im nearing a scary deadline.

**Comment by HereafterMills** [comment]
Nevermind. I managed to solve this one. Was a BP error
