### ISSUE TITLE
Android crashing when connecting to voice?

### ISSUE THREAD

**Issue by HereafterMills** [AgoraIO-Extensions/Agora-Unreal-RTC-SDK#101]
[phoneLogs.log](https://github.com/AgoraIO-Extensions/Agora-Unreal-RTC-SDK/files/13257808/phoneLogs.log)

Hi @WinterPu 
My device crashes when trying to connect. 

It was working before when the BP issue was blocking initialization. And also was working fine when i tried with development. 

Have attached the phone logs. 

11-05 03:19:34.872 16432 16432 F DEBUG   :       #00 pc 000000000008d394  /apex/com.android.runtime/lib64/bionic/libc.so (abort+168) (BuildId: 1bcad8bca80d38bceb9089f70d394e33)
11-05 03:19:34.872 16432 16432 F DEBUG   :       #01 pc 0000000000796de0  /data/app/~~32TJa3yzuguFVohMblnrqw==/com.Hereafter.ToolboxVR-EIxwqkZjlL73HryQZHtREw==/lib/arm64/libagora-rtc-sdk.so (BuildId: 6cb66a6723d86bdb90aa474e20aa942553887ca4)
11-05 03:19:34.872 16432 16432 F DEBUG   :       #02 pc 0000000000ce7584  /data/app/~~32TJa3yzuguFVohMblnrqw==/com.Hereafter.ToolboxVR-EIxwqkZjlL73HryQZHtREw==/lib/arm64/libagora-rtc-sdk.so (BuildId: 6cb66a6723d86bdb90aa474e20aa942553887ca4)
11-05 03:19:34.872 16432 16432 F DEBUG   :       #03 pc 0000000000ce7740  /data/app/~~32TJa3yzuguFVohMblnrqw==/com.Hereafter.ToolboxVR-EIxwqkZjlL73HryQZHtREw==/lib/arm64/libagora-rtc-sdk.so (BuildId: 6cb66a6723d86bdb90aa474e20aa942553887ca4)
11-05 03:19:34.872 16432 16432 F DEBUG   :       #04 pc 0000000000ce881c  /data/app/~~32TJa3yzuguFVohMblnrqw==/com.Hereafter.ToolboxVR-EIxwqkZjlL73HryQZHtREw==/lib/arm64/libagora-rtc-sdk.so (BuildId: 6cb66a6723d86bdb90aa474e20aa942553887ca4)
11-05 03:19:34.872 16432 16432 F DEBUG   :       #05 pc 0000000000bcf2b4  /data/app/~~32TJa3yzuguFVohMblnrqw==/com.Hereafter.ToolboxVR-EIxwqkZjlL73HryQZHtREw==/lib/arm64/libagora-rtc-sdk.so (BuildId: 6cb66a6723d86bdb90aa474e20aa942553887ca4)
11-05 03:19:34.872 16432 16432 F DEBUG   :       #06 pc 0000000000befffc  /data/app/~~32TJa3yzuguFVohMblnrqw==/com.Hereafter.ToolboxVR-EIxwqkZjlL73HryQZHtREw==/lib/arm64/libagora-rtc-sdk.so (JNI_OnLoad+104) (BuildId: 6cb66a6723d86bdb90aa474e20aa942553887ca4)

**Comment by HereafterMills** [comment]
[APL_armv7.zip](https://github.com/AgoraIO-Extensions/Agora-Unreal-RTC-SDK/files/13257842/APL_armv7.zip)

I did modify this to not include Enable video and read state, because the oculus store does not allow it. Could this be the reason?

**Comment by WinterPu** [comment]
Currently, I am unable to find any useful information from the symbols.  Could you find the agorasdk.log or agoraapi.log in App Folder?  Alternatively, you can submit a support ticket in [Agora Support](https://www.agora.io/en/talk-to-us/). . By providing your appId or other relevant information, we can assist in searching for any useful details.

**Comment by WinterPu** [comment]
For the APL_armv7.zip file, I believe it should be fine because we have a Voice SDK that doesn't have Camera Permission. Additionally, you could restore the phone state to see if it crashes. I will look into it later.

**Comment by HereafterMills** [comment]
Closing this, as an update is here: https://github.com/AgoraIO-Extensions/Agora-Unreal-RTC-SDK/issues/109
