### ISSUE TITLE
Windows SDK not found

### ISSUE THREAD

**Issue by HereafterMills** [AgoraIO-Extensions/Agora-Unreal-RTC-SDK#102]
Hi, 

In AgoraPlugin.cpp, there might be an issue in line 18:

	LibraryPath = FPaths::Combine(*BaseDir, TEXT("Source/ThirdParty/AgoraPluginLibrary/x64/Release/agora_rtc_sdk.dll"));

Should the path of the sdk should be x86_64, not x64, and the other way around?

The path i have in my local plugins folder is : Plugins\AgoraPlugin\Source\ThirdParty\AgoraPluginLibrary\Win\Release\x86_64

And my windows packaged game log gives me the error: [2023.11.05-15.57.54:217][  0]LogWindows: Failed to load '../../../XXXX/Plugins/AgoraPlugin/Source/ThirdParty/AgoraPluginLibrary/x64/Release/agora_rtc_sdk.dll' (GetLastError=126)

**Comment by WinterPu** [comment]
Thanks for pointing it out. This is used for testing and it would be fixed in the coming version.

**Comment by icywind** [comment]
The path has been fixed in [the current release.](https://github.com/AgoraIO-Extensions/Agora-Unreal-RTC-SDK/blob/b08edb070c3925bded5cf32ccba3935bbac27f8e/Agora-Unreal-SDK-CPP/AgoraPlugin/Source/AgoraPlugin/Private/AgoraPlugin.cpp#L4)  Thanks for the feedback!
