### ISSUE TITLE
Mac Issue with Mic

### ISSUE THREAD

**Issue by HereafterMills** [AgoraIO-Extensions/Agora-Unreal-RTC-SDK#107]
As i notice @WinterPu You updated the readme with an update for unreal 5 with mac. 

I tried this, however, when opening the plist within unreal at the path you mentioned, there is already a mic permission mentioned there. 

Unsure of what to do with that. 

At the moment we have no mic access on mac.

**Comment by WinterPu** [comment]
That is used to add the Camera permission. I noticed that if you directly change the info.plist in your app, it may not work well 佛for UE5. Another way to do it is by modifying the info.plist template in the Build/Mac/Resources folder under your project.

**Comment by HereafterMills** [comment]
I dont seem to have a Build/Mac/Resources in my project folder. Should i make it?

**Comment by WinterPu** [comment]
No, in this case, which version of UE are you using?

**Comment by HereafterMills** [comment]
Im using UE5.2.

**Comment by HereafterMills** [comment]
Post build, i have been running this: 

    write_note(f'Adding plist entries in: {app_path}')
    os.system("/usr/libexec/PlistBuddy -c \"Add :NSCameraUsageDescription string Required for videos so others can see you\" "+app_path+"/Contents/Info.plist >> "+mac_log_file) 
    os.system("/usr/libexec/PlistBuddy -c \"Add :NSMicrophoneUsageDescription string Required for voice to talk to others\" "+app_path+"/Contents/Info.plist >> "+mac_log_file) 
    os.system("/usr/libexec/PlistBuddy -c \"Add :NSPhotoLibraryUsageDescription string Required for Avatar Manager\" "+app_path+"/Contents/Info.plist >> "+mac_log_file)
    os.system("/usr/libexec/PlistBuddy -c \"Add :NSPhotoLibraryAddUsageDescription string Required for Avatar Manager\" "+app_path+"/Contents/Info.plist >> "+mac_log_file) 
    os.system("/usr/libexec/PlistBuddy -c \"Set :CFBundleVersion "+str(package_version)+"\" "+app_path+"/Contents/Info.plist >> "+mac_log_file)
    os.system("/usr/libexec/PlistBuddy -c \"Set :CFBundleShortVersionString "+str(package_version)+"\" "+app_path+"/Contents/Info.plist >> "+mac_log_file) 
    os.system("/usr/libexec/PlistBuddy -c \"Add :LSApplicationCategoryType string public.app-category.education\" "+app_path+"/Contents/Info.plist >> "+mac_log_file)

**Comment by HereafterMills** [comment]
This issue still persists. Have changed the engine plist as well, changed project plist as well. Can connect to voice channel, but no one can hear me.

**Comment by WinterPu** [comment]
You could try [tccutil reset Microphone] to reset the permission and see if it works. Additionally, could you identify if this is a permission problem? Does it work in PIE (Play in Editor)？

**Comment by HereafterMills** [comment]
Just tested. 

tccutil reset Microphone didnt do anything for me. 

However, voice did work in the editor just fine during PIE

**Comment by WinterPu** [comment]
When you changed the info.plist template of your engine, did the app you packaged have the required permission? It should have.

**Comment by HereafterMills** [comment]
Hey @WinterPu 
Did you manage to figure this one out? Im still crashing.

**Comment by WinterPu** [comment]
I have no idea. How did you conclude that this crash is related to the SDK?

**Comment by HereafterMills** [comment]
Is libtbb.dylib not part of the agora package?

Reason: tried: '/Users/raahilkulshreshtha/Documents/Projects/Surrogate/Packages/Build5.7_2024_08_09_03/Mac/Main/Surrogate.app/Contents/UE/Engine/Binaries/Mac/CrashReportClient.app/Contents/MacOS/libtbb.dylib' (no such file), '/Users/raahilkulshreshtha/Documents/Projects/Surrogate/Packages/Build5.7_2024_08_09_03/Mac/Main/Surrogate.app/Contents/UE/Engine/Binaries/Mac/CrashReportClient.app/Contents/MacOS/libtbb.dylib' (no such file), '/Users/raahilkulshreshtha/Documents/Projects/Surrogate/Packages/Build5.7_2024_08_09_03/Mac/Main/Surrogate.app/Contents/UE/Engine/Binaries/Mac/libtbb.dylib' (no such file), '/Users/raahilkulshreshtha/Documents/Projects/Surrogate/Packages/Build5.7_2024_08_09_03/Mac/Main/Surrogate.app/Content

**Comment by WinterPu** [comment]
Doesn't seem like

https://en.wikipedia.org/wiki/Threading_Building_Blocks

**Comment by HereafterMills** [comment]
This was fixed. For anyone wanting to know how, you need to update both the plist and the entitlements now.
