### ISSUE TITLE
New SDK version and Mac

### ISSUE THREAD

**Issue by HereafterMills** [AgoraIO-Extensions/Agora-Unreal-RTC-SDK#108]
Hi. 

On mac, i had to revert back to the older sdk (from 2 weeks ago), because all the framework files were giving an error during the build process. 

Just FYI

**Comment by WinterPu** [comment]
Hi, could you please show me your log and what you did? Did you run the BuildPlugin command?

**Comment by WinterPu** [comment]
We keep the symbolic links for Mac frameworks. This can reduce the size of the frameworks and would be used in your codesign process for Mac.

**Comment by HereafterMills** [comment]
Im using the launcher version of unreal on the mac since the source version doesnt work well with Xcode15. 

What is the specific buildplugin command you are refering to? 

Also, note that the plugin currently resides in my project plugin folder and not the engine

**Comment by WinterPu** [comment]
I mean UAT's BuildPlugin command: https://dev.epicgames.com/community/learning/tutorials/qz93/unreal-engine-building-plugins. Could you show me your error log pls? Also which UE version are you using?

**Comment by HereafterMills** [comment]
Using UE5.2. I havent built the plugin, but i do build the project and each target. I assumed that was enough. Will give this a shot tomorrow as well.

**Comment by WinterPu** [comment]
You could also try **[ cp -r YourMacFrameworkFolder  YourMacFrameworkFolderDst ]**  (YourMacFrameworkFolder is under the Plugins\AgoraPlugin\Source\ThirdParty\AgoraPluginLibrary\. ) and replace YourMacFrameworkFolder  with YourMacFrameworkFolderDst to see if the issue has been fixed.  If it does help, your build process may involve SafeCopy.

**Comment by HereafterMills** [comment]
I shall test and report back. Thanks.

**Comment by HereafterMills** [comment]
> You could also try **[ cp -r YourMacFrameworkFolder YourMacFrameworkFolderDst ]** (YourMacFrameworkFolder is under the Plugins\AgoraPlugin\Source\ThirdParty\AgoraPluginLibrary. ) and replace YourMacFrameworkFolder with YourMacFrameworkFolderDst to see if the issue has been fixed. If it does help, your build process may involve SafeCopy.

You were correct. The issue was that i had zipped up the agora plugin on windows, and unzipped that file on Mac. Downloading the files directly did the trick.
