### ISSUE TITLE
Issue with Android with the -distribution configuration. 

### ISSUE THREAD

**Issue by HereafterMills** [AgoraIO-Extensions/Agora-Unreal-RTC-SDK#109]
Hi, 

Agora seems to be crashing unreal packaged builds on android when uploading them on any of the android stores. Be it Play store, Oculus store and in my case, the Pico store.  All android related. 

I was able to narrow down the issue, where it would crash on android only if the -distribute tag (For Distribution - In Project Settings>Packaging) is included in the build.

If i make a shipping build **without** the -distribution flag, it works fine, but with the -distribution flag, it crashes consistently when calling the "Initialize" node. 

To be clear, `Everything works seamlessly without the -distribution flag`. This i have tested extensively.

Seems to be a similar issue to what @joeholee talks about here: https://github.com/AgoraIO-Extensions/Agora-Unreal-RTC-SDK/issues/75

`Apps packaged with For Distribution enabled work when sideloading via adb as well. In my case, sideloading also crashed when Initialize was called, which was helpful as i can now recreate the issue without having to upload to the store. `

This is after the RTCEngine and EventHandler have been defined. Heres a screenshot of my test setup:

![image](https://github.com/AgoraIO-Extensions/Agora-Unreal-RTC-SDK/assets/37168482/ac34aa2f-59c4-41bb-bf79-ecb0d6cc08d0)

Its a very simple setup just to test. I was able to narrow down the issue to the 'Initialize' node by trial and error. 

The logcat logs are here. This was a development build with -distribute, so theres plenty of debugging info. 

[phoneLogs.log](https://github.com/AgoraIO-Extensions/Agora-Unreal-RTC-SDK/files/13537072/phoneLogs.log)

(While this logcat output has unreal logs as well, the actual unreal logs wrote nothing about the crash, just stopped). 

I also have the READ_PHONE_STATE permission enabled, so its not because of that. 

This is the command im using to package:
Engine\Build\BatchFiles\RunUAT.bat BuildCookRun -unrealexe="Engine\Binaries\Win64\UnrealEditor-Cmd.exe" -project="D:\xxx\xxx.uproject" -ScriptsForProject=D:\xxx\xxx.uproject -target=xxx -targetplatform=Android -stage -package -build -cook -compile -archive -archivedirectory="D:\xxx\Packages\xxx_351_4.9\Temp\Main"  -nocompileeditor -noP4 -SkipCookingEditorContent -prereqs -log -compressed -CrashReporter -utf8output -ForceDebugInfo -nativizeAssets -manifests -pak -distribution -platform=Android -cookflavor=ASTC -clientconfig=Development

With these config variables:
MinSDKVersion=27
TargetSDKVersion=33
InstallLocation=Auto
bEnableLint=False
bPackageDataInsideApk=True
bCreateAllPlatformsInstall=False
bDisableVerifyOBBOnStartUp=False
bForceSmallOBBFiles=False
bAllowLargeOBBFiles=True
bAllowPatchOBBFile=False
bAllowOverflowOBBFiles=False
bUseExternalFilesDir=True

I dont think any of this is related, but just giving as much info as i can.

Im also closing all the other android related threads i opened since this is the core of them all. 

Submitted a support ticket as well here - https://agora-ticket.agora.io/issue/bc0c832f7d884ad2925c72d7db603fd9

Im getting a little concerned to be honest. If i dont have this running within this week, my client will ask me to shift back to Vivox, and i really dislike working with vivox. Please help.

**Comment by WinterPu** [comment]
Thank you very much, I will look into it.

**Comment by HereafterMills** [comment]
Hey. Any luck with this one?

**Comment by WinterPu** [comment]
Currently, I am still working on reproducing this error.

**Comment by HereafterMills** [comment]
It's strange that it's not happening for you by default. The only thing
different for us could be the android sdk and ndk setup. Target sdk for me
is both 32 and 33 that iv tested. Could it be a matter of the sdk and ndk
override?

**Comment by WinterPu** [comment]
I don't think so. I am working on it.

**Comment by WinterPu** [comment]
Hi, I noticed this error:

12-03 00:01:15.587 20779 20843 E rtc     : #
12-03 00:01:15.587 20779 20843 E rtc     : # Fatal error in: ../../../../../media_sdk_script/media_engine2/webrtc/modules/utility/source/helpers_android.cc, line 74
12-03 00:01:15.587 20779 20843 E rtc     : # last system error: 88
12-03 00:01:15.587 20779 20843 E rtc     : # Check failed: !jni->ExceptionCheck()
12-03 00:01:15.587 20779 20843 E rtc     : # Error during FindClass: io/agora/base/internal/voiceengine/BuildInfo

It appears that the class **[io/agora/base/internal/voiceengine/BuildInfo]** failed to load. Could you please verify if the **[agora-rtc-sdk.jar]** is located in the correct directory? Additionally, you may want to check the **APL_armv7.xml** file in the **[\AgoraPlugin\Source\ThirdParty\AgoraPluginLibrary\Android\Release]** directory.

To investigate further, you can use **jd-gui** to open the jar file. This tool should be able to help you locate the class in question.

<img width="327" alt="image" src="https://github.com/AgoraIO-Extensions/Agora-Unreal-RTC-SDK/assets/12077942/464cbdd2-41e2-4b87-b278-c5a44cb1dac0">

**Comment by HereafterMills** [comment]
> Hi, btw, I noticed this error:
> 
> 12-03 00:01:15.587 20779 20843 E rtc : # 12-03 00:01:15.587 20779 20843 E rtc : # Fatal error in: ../../../../../media_sdk_script/media_engine2/webrtc/modules/utility/source/helpers_android.cc, line 74 12-03 00:01:15.587 20779 20843 E rtc : # last system error: 88 12-03 00:01:15.587 20779 20843 E rtc : # Check failed: !jni->ExceptionCheck() 12-03 00:01:15.587 20779 20843 E rtc : # Error during FindClass: io/agora/base/internal/voiceengine/BuildInfo
> 
> It appears that the class **[io/agora/base/internal/voiceengine/BuildInfo]** failed to load. Could you please verify if the **[agora-rtc-sdk.jar]** is located in the correct directory? Additionally, you may want to check the **APL_armv7.xml** file in the **[\AgoraPlugin\Source\ThirdParty\AgoraPluginLibrary\Android\Release]** directory.
> 
> To investigate further, you can use **jd-gui** to open the **[agora-rtc-sdk.jar]** jar file.
> <img alt="image" width="327" src="https://private-user-images.githubusercontent.com/12077942/287911226-464cbdd2-41e2-4b87-b278-c5a44cb1dac0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE3NTU1MzgsIm5iZiI6MTcwMTc1NTIzOCwicGF0aCI6Ii8xMjA3Nzk0Mi8yODc5MTEyMjYtNDY0Y2JkZDItNDFlMi00Yjg3LWIyNzgtYzVhNDRjYjFkYWMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA1VDA1NDcxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNlYTI4OTMwZjE3MDE4NWFkZTNlZjZmNjIwOTgwMmEwODYxYzk4M2EwODBlZDM4YzhjYzlkYzYwYWM3MTRjODAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._TQVPTCb5vKNXoT-PCbXcl0VEVn6fjSDpJiB_OMH1hc">

This is my Android/Release directory where the jar file also exists:
![image](https://github.com/AgoraIO-Extensions/Agora-Unreal-RTC-SDK/assets/37168482/6fd00615-b373-4abf-907e-bc7cd8bb8014)

This is my APL_armv7 file (Github not allowing xml so have zipped it):
[APL_armv7.zip](https://github.com/AgoraIO-Extensions/Agora-Unreal-RTC-SDK/files/13555751/APL_armv7.zip)

This is all the open files in that folder:

[Release.zip](https://github.com/AgoraIO-Extensions/Agora-Unreal-RTC-SDK/files/13555762/Release.zip)


And this is what JDGUI shows:
![image](https://github.com/AgoraIO-Extensions/Agora-Unreal-RTC-SDK/assets/37168482/023ae5be-875e-4ba1-a569-ac9168a32fcb)

Hope this helps!

**Comment by WinterPu** [comment]
Hi, the previous error was caused by proguard. The names would have been changed so the class could not load. 
You can add the following code under **gameActivityImportAdditions** in your **APL_armv7Template.xml**:

```
	<proguardAdditions>
		<insert>
			-keep class io.agora.** { *; }
		</insert>
	</proguardAdditions>
```

This would disable proguard for agora-rtc-sdk.jar. To verify if it is successful, you can use the d2j tool to convert your class.dex in your apk to a jar. Then, use jd-gui to check if the class names have been changed.

**Comment by WinterPu** [comment]
I mean they are on the same level. I have modified the sample code. Also you could check your class.dex in your apk.

**Comment by HereafterMills** [comment]
Can i send you my apk?

**Comment by WinterPu** [comment]
You could check the file \Intermediate\Android\arm64\gradle\app\proguard-rules.pro if it has added  [-keep class io.agora.** { *; } ], then you could also use [..\Intermediate\Android\arm64\gradle rungradle.bat :app:assembleRelease] to build your app directly from the generated android project.

**Comment by HereafterMills** [comment]
[proguard-rules.zip](https://github.com/AgoraIO-Extensions/Agora-Unreal-RTC-SDK/files/13582928/proguard-rules.zip)

My proguard-rules.pro doesnt seem to have -keep class io.agora.** { *; 

What could that mean? Iv crosschecked, and APL_armv7.xml does have the lines you mentioned, though i assume this is the correct format and place for them. 

[APL_armv7.zip](https://github.com/AgoraIO-Extensions/Agora-Unreal-RTC-SDK/files/13582939/APL_armv7.zip)

**Comment by WinterPu** [comment]
Have you made it?

**Comment by HereafterMills** [comment]
Honestly, im still struggling to create an APK from that folder at the moment. Im not very well versed with native android packaging so theres a bit of a learning curve for me on that front.

**Comment by WinterPu** [comment]
You could use Android Studio to open the [gradle] folder and package your app from that.

**Comment by HereafterMills** [comment]
I tried that but android studio throws these errors; 
![image](https://github.com/AgoraIO-Extensions/Agora-Unreal-RTC-SDK/assets/37168482/715eb5e5-c6b9-4e22-8277-5f423a30c112)
Have since been trying to build using aapt manually.

Would i be possible for me to send you my \Intermediate\Android\ folder via wetransfer?

**Comment by WinterPu** [comment]
I would talk to you later.
