### ISSUE TITLE
I've been using Agora plugin in my Unreal Project. It works fine on Windows but gives these unknown symbols & linker error on Mac. Any idea how to resolve it?

### ISSUE THREAD

**Issue by saswat-mishra** [AgoraIO-Extensions/Agora-Unreal-RTC-SDK#112]
![IMG_20240314_195234](https://github.com/AgoraIO-Extensions/Agora-Unreal-RTC-SDK/assets/32617481/eed558f6-ffc8-4be5-bd12-5e6fba4a28e1)

I'm using Unreal Engine 5.0.3 source code build in MacOS Monterey with Xcode 13.4.1 with Intel i7 processor

**Comment by WinterPu** [comment]
Which version of UE are you using? You could try to select the proper architecture (ex. Universal)  in : your [Project Settings] -> [Platforms] -> [Mac] ->[Packaging], or modify it in your UE config ini file.
