### ISSUE TITLE
Packaging error in iOS with xcode 13.4

### ISSUE THREAD

**Issue by saswat-mishra** [AgoraIO-Extensions/Agora-Unreal-RTC-SDK#114]
I'm getting this error:
ld: '/Users/ec2-user/Documents/UnrealEngine/Engine/Intermediate/UnzippedFrameworks/AgoraVideoSegmentationExtension/AgoraVideoSegmentationExtension.framework/AgoraVideoSegmentationExtension' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. file '/Users/ec2-user/Documents/UnrealEngine/Engine/Intermediate/UnzippedFrameworks/AgoraVideoSegmentationExtension/AgoraVideoSegmentationExtension.framework/AgoraVideoSegmentationExtension' for architect ure arm64

Followed by linker error.

Also I can't find the "Enable Bitcode" option in XCode as most people give this as a solution. I literally searched it across all targets inside Build settings & changed to "all" tab from "basic" but no such option.

**Comment by WinterPu** [comment]
I remember Apple has given up the bitcode. I don't have Xcode 13.4. Maybe you could try to build it with different iOS Deployment Target version.
