### ISSUE TITLE
Android Crash!  During Rtc initialize

### ISSUE THREAD

**Issue by utitaku** [AgoraIO-Extensions/Agora-Unreal-RTC-SDK#116]
UE5.1  Android Pakaged.  Agora SDK 4.2.1

I am using UE blueprints, but it crashes on Agora initialize.
If I don't initialize, the rest of the game can be played without problems.

UE Package Configuration >  #106 

MinSDKVersion=27
TargetSDKVersion=33
InstallLocation=Auto
bPackageDataInsideApk=False
bAllowLargeOBBFiles=True
bUseExternalFilesDir=True

SDK
![image](https://github.com/AgoraIO-Extensions/Agora-Unreal-RTC-SDK/assets/79887893/c6151544-1f64-4690-992f-977567854aa1)

Are there any other settings that we should be aware of?
(e.g., permissions, etc.)

**Comment by WinterPu** [comment]
Maybe you could try this one https://github.com/AgoraIO-Extensions/Agora-Unreal-RTC-SDK/issues/109#issuecomment-1842572168

**Comment by utitaku** [comment]
Thank you very much. That was correct.

Just adding the code solved the problem!
