### ISSUE TITLE
Logs

### ISSUE THREAD

**Issue by HereafterMills** [AgoraIO-Extensions/Agora-Unreal-RTC-SDK#120]
Hi @WinterPu 
Im starting on a new project. And i see that when joining a new map, i get a crash in a packaged game. This is kinda similar to what was happening in the editor months back. The way i sidestepped that is by disabling the RTC engine in the editor. 

Once i have logs, i can post here, but im unable to find the area to generate them for agora. 

Thanks.

**Comment by WinterPu** [comment]
You could check this one: https://docs.agora.io/en/help/integration-issues/log

**Comment by HereafterMills** [comment]
Thanks. I was able to generate the logs. Do you see anything significant in the attached files? I crash when trying to connect after joining map no. 2 every single time. 
[logs.zip](https://github.com/user-attachments/files/16431825/logs.zip)

**Comment by WinterPu** [comment]
No, it's better to check the call stack to see the crash point. I guess you could pay attention to the RTC engine instance you keep between two different maps.

**Comment by HereafterMills** [comment]
![image](https://github.com/user-attachments/assets/7a2c1d07-9a37-4519-95d2-ad18b7580be9)
I tried debugging with attach to process, and this is what i get on the crash

**Comment by HereafterMills** [comment]
Btw, im getting the same behaviour in the editor. If i play in editor, and then stop that, then play again, i get a crash. 

This is what i get in the editor:
![image](https://github.com/user-attachments/assets/99a73bbe-f4e2-41df-8387-d42abca6ff39)

**Comment by HereafterMills** [comment]
Another log from unreal that may help

[Surrogate.log](https://github.com/user-attachments/files/16440253/Surrogate.log)

**Comment by WinterPu** [comment]
This log does not show each module's base address, so I could not locate the actual function it used.
Could you pls send me a dump file (a full dump would be better)？

**Comment by HereafterMills** [comment]
Have attached the dmp files. Not sure if these are full or mini. 
Link is here:  https://we.tl/t-Qwq1ubI3Up


This includes the pdb files as well. 
One thing i can confirm, is that if i run the same code within the same map, connect-leavechannels-connect_again (while skipping rtc init, it all works fine. But if i add a map change in the middle, it crashes. So its likely that its something to do with the RTC Engine instance itself as you mentioned. However, the RTC Engine resides in the game instance, which shouldnt get destroyed, so im a bit confused as to why thats happening.

**Comment by HereafterMills** [comment]
Also, just so you know what im doing. When joining a new map, i run this on the game instance:
![image](https://github.com/user-attachments/assets/918c9271-d19e-4aea-a8fb-532d8f79fd1a)
![image](https://github.com/user-attachments/assets/26e8d180-2778-4128-9b24-a3a63ce2b205)
The Agora Join function is basically just to get the token and connect to a channel using Join Channel with User Account.

**Comment by HereafterMills** [comment]
I can confirm that the RTC engine is not maintained while moving to a new map. This is strange, since i have plenty of checks to ensure that its never overwritten. or cleared What am i doing wrong here?
![image](https://github.com/user-attachments/assets/06c7095e-1efa-4a62-a874-4914fcff9e43)
This is the only place in all the blueprints where im setting its value.

**Comment by HereafterMills** [comment]
Well that was embarrassing. I totally missed the outer for the RTC engine. Thanks for your time @WinterPu and apologies for wasting it.
