### ISSUE TITLE
blueprint project not working on 4.27.2 or UE5.0.3 and CPP project not working on UE5.0.3

### ISSUE THREAD

**Issue by YousefBadr** [AgoraIO-Extensions/Agora-Unreal-RTC-SDK#29]
**I want to make it work on UE5. either the CPP project or the blueprint project.**

**Problem with Example CPP project:**
UE5.0.3:
Refuses to compile giving me these errors in the engine:

![image](https://user-images.githubusercontent.com/45340990/192161597-a4de8de0-f654-4a3b-869f-867a3132999f.png)
UE4.27.2: Works Greatly! no errors.

**Problem with Example Blueprint project:**
UE5.0.3 and UE4.27.2:
they compile successfully and open. but packaging fails with theses errors.

[PackagingLog.txt](https://github.com/AgoraIO-Extensions/Agora-Unreal-RTC-SDK/files/9641641/PackagingLog.txt)

Opening any map of these I get similar errors to the following:

![image](https://user-images.githubusercontent.com/45340990/192162002-c79fc73f-277a-4368-8160-f20116ff58de.png)
![image](https://user-images.githubusercontent.com/45340990/192162009-e67c208a-a0f7-4748-8032-1a35a2cd6ef9.png)

![image](https://user-images.githubusercontent.com/45340990/192162103-dcbea963-e202-4976-9d51-35e16af7d19a.png)

What could possibly be the problem ?

**Comment by oneSitDown** [comment]
Thank you very much for your feedback, we have not yet submitted the sdk version of the adaptation blueprint. Later you can use the blueprint function in version 4.0.0.5

**Comment by YousefBadr** [comment]
> Thank you very much for your feedback, we have not yet submitted the sdk version of the adaptation blueprint. Later you can use the blueprint function in version 4.0.0.5

Thanks for replying, for now, how can I fix the CPP project not compiling on UE5? do I have to wait for sdk 4.0.0.5 too ?

**Comment by oneSitDown** [comment]
You can download it now, 4.0.0.5 has been released。"Texture" This problem is caused by ue5 updated api. We've fixed it, you just pull the latest code and it should work.
