### ISSUE TITLE
Windows Defender Detects virus in repo and packaged game

### ISSUE THREAD

**Issue by YousefBadr** [AgoraIO-Extensions/Agora-Unreal-RTC-SDK#35]
Windows Defender on windows 11 detects a virus in the downloaded repo and prevents the packaged build from running.

![image](https://user-images.githubusercontent.com/45340990/192299616-03114ff1-2d27-444d-9048-dfd69f970cbf.png)

I scanned the packaged build and downloaded repo using Malwarebytes but it says it's all safe, no viruses.
I know windows defender can be over protective but why it prevents the app from running ? 
we are launching the app on windows and this is going to be a problem.
Thanks in advance.

**Comment by oneSitDown** [comment]
Do you mean that running the packaged exe on a Windows 11 computer will have a virus prompt and will prevent the program from running? We are currently debugging the program on win10 and have never encountered the problem you mentioned. Do you also encounter this problem on your win10 computer?

**Comment by oneSitDown** [comment]
I asked about QA this morning, and he confirmed that it covered win11, saying that the virus has never been reported.

**Comment by YousefBadr** [comment]
I've tried it on windows 10 windows defender and it says it's safe. I think it's a problem with windows 11 only. I will apply latest update "Windows 11, version 22H2" and will write back here.

**Comment by YousefBadr** [comment]
Still same problem exists.
![image](https://user-images.githubusercontent.com/45340990/192839478-63fe0518-6575-4b27-ad66-2f829b27f0f2.png)

**Comment by oneSitDown** [comment]
ok，are you use unreal5？

**Comment by YousefBadr** [comment]
Yes, I'm using UE5. and it works greatly. 
It detects the repos as a virus once I hit download. it has nothing to to with the engine.
Anyhow thanks for replying I'll keep a close eye when it's fixed.
