### ISSUE TITLE
LinuxServer AWS-Gamelift Failed build.

### ISSUE THREAD

**Issue by davidherran** [AgoraIO-Extensions/Agora-Unreal-RTC-SDK#36]
Hello there, we are using Agora for our virtual world - metaverse based.
The project has some compilation problems in the server, we are using Linux to compile because of using AWS as the dedicated server.

Have you tried to compile for Linux Server?

We could fix some problems by deleting the module that we created to add Agora to our project that has all the cpp classes. But the build is still crashing trying to run it in the server (through gamelift).

So we decided to try first your template project, we are still having a lot of compilations errors, some of them appear on windows and linux server builds, we are concerned that Agora will not work for linux.
I hope that you can help us.

**Comment by oneSitDown** [comment]
We currently do not support LinuxServer, but only support compiling under mac or windows. Can you tell us what errors are reported in windows compilation? Yesterday we updated the 4.0.0.5alpha version, please try to see if there is still a problem with windows

**Comment by davidherran** [comment]
Hello again, we are trying to compile the agora implementation in a new project and we have some errors using the newest template's versions.
We just created a new module to put all your classes.

Two of us tried to do the same, in one of the projects we have a bunch of errors and warnings:
![image](https://user-images.githubusercontent.com/7173954/192667698-44065987-60bc-4342-b31d-eb2655d2dd6a.png)

This is with another project:
![image](https://user-images.githubusercontent.com/7173954/192667246-ae956f07-5030-4cd8-a2fc-1927c54fc600.png)

**Comment by oneSitDown** [comment]
please pull lastest code,and ues 4.0.0.5 SDK,this error is fixed

**Comment by davidherran** [comment]
Hi. Thanks!

we are already using your last version (4.0.0.5), but what errors are you talking about? We try build Agora-Unreal-SDK-CPP-Example project, and we get above errors.

**Comment by oneSitDown** [comment]
I have also encountered these problems with you, such as onVideoSizeChange, which I have commented on in the latest example. It is impossible for this problem to occur.

**Comment by mcianni** [comment]
> Hello there, we are using Agora for our virtual world - metaverse based. The project has some compilation problems in the server, we are using Linux to compile because of using AWS as the dedicated server.
> 
> Have you tried to compile for Linux Server?
> 
> We could fix some problems by deleting the module that we created to add Agora to our project that has all the cpp classes. But the build is still crashing trying to run it in the server (through gamelift).
> 
> So we decided to try first your template project, we are still having a lot of compilations errors, some of them appear on windows and linux server builds, we are concerned that Agora will not work for linux. I hope that you can help us.

Hi @davidherran! Sorry for the random message, but I'm working on something similar and am interested in getting this working on Linux. Were you successful?

**Comment by davidherran** [comment]
Hi. Copy to my partner.
