### ISSUE TITLE
Editor crashing for BP project

### ISSUE THREAD

**Issue by Shumaro211** [AgoraIO-Extensions/Agora-Unreal-RTC-SDK#38]
Hello there.
I'm testing the BP project, I'm using your last submissions for the plugin and template and every action I try to do results in the editor crashing. All the actions: Join channel audio, Screen Share, etc. do the same, it seems like the corresponding map is being open but then it crash. 
![image](https://user-images.githubusercontent.com/66711189/192819266-5a4e1c90-8100-4b23-9f43-84927bb992e8.png)

**Comment by oneSitDown** [comment]
What platform editor do you use? If it is a mac, you need to open the permission to use it. Otherwise, it will crash。

**Comment by oneSitDown** [comment]
What platform editor do you use? If it is a mac, you need to open the permission to use it. Otherwise, it will crash。

**Comment by Shumaro211** [comment]
I'm using Windows 10.

**Comment by oneSitDown** [comment]
你能在D:/Agora-Unreal-SDK-Blueprint-Example/Plugins/AgoraPlugin/Source/ThirdParty/AgoraPluginLibrary/x64/Release/agora_rtc_sdk.dll这个路径找到库文件吗？是不是有可能是病毒误杀了？或者解压错误导致文件丢失？

**Comment by Shumaro211** [comment]
We have ddl files, but that root doesn't exist, I also looked for it in the zip and is not there.
![image](https://user-images.githubusercontent.com/66711189/192838601-82c498af-0efe-4af0-841e-4ef239570857.png)

**Comment by oneSitDown** [comment]
It may not be possible for you to temporarily change the name of this x86_64 to x64. We are now at 00:51, and we may have to go to the company tomorrow to reproduce this problem directly, sorry.

**Comment by Shumaro211** [comment]
How can I clone the plugin? I'm trying with commands and github desktop but they are giving me errors.
I could clone the template, not the plugin.

**Comment by oneSitDown** [comment]
The plugin is version 4.0.0.5 downloaded from release, not a clone. After the download is complete, copy it to the plugins folder of the project directory. For details, please refer to the readme.
https://github.com/AgoraIO-Extensions/Agora-Unreal-RTC-SDK/blob/main/Agora-Unreal-SDK-CPP-Example/README.md
