### ISSUE TITLE
Enable Virtual Background not working!

### ISSUE THREAD

**Issue by YousefBadr** [AgoraIO-Extensions/Agora-Unreal-RTC-SDK#39]
Hi, I want to replace green background with a translucent one. but when I call enable virtual background it replaces green screen with a grey one.

The original Video with "enable virtual background" turned off:
![image](https://user-images.githubusercontent.com/45340990/192873617-8069b627-d882-4af4-8833-f3c5f57240fa.png)

The Output I need:
![image](https://user-images.githubusercontent.com/45340990/192874608-08b5f7d9-2f9a-47f6-80fa-dd099986663a.png)

The Output I get after calling "enable virtual background" with the following inputs before joining channel:
![image](https://user-images.githubusercontent.com/45340990/192873743-cc6ed0c7-aeca-46b6-a16a-605cc7e9af4f.png)

The Settings:
![image](https://user-images.githubusercontent.com/45340990/192874027-8108852b-4fdf-4bc2-b489-2b6e730875d4.png)

What can I do to fix it?
I'm Using UE5 and Plugin Version: Agora_Unreal_RTC_Blueprint_SDK_4.0.0-alpha.1_FULL.zip

Thanks in advance. I visited this plugin 3 months ago and I can say that you did a great job!

**Comment by oneSitDown** [comment]
We currently only support the gray，can't get a picture with a transparent。
