### ISSUE TITLE
Build for AWS

### ISSUE THREAD

**Issue by Shumaro211** [AgoraIO-Extensions/Agora-Unreal-RTC-SDK#40]
Hello there. 
Do you know someone that uses AWS with Agora? either with linux or windows.

All our testing with the different plugins/templates you have is to solve the server crashing problem which is: SERVER_PROCESS_CRASHED
"Server process exited without calling ProcessEnding(), exitCode(-1073741515),...

The build deploy could run in AWS just enabling the plugin, but it failed when we implemented your Agora classes as a module (we didn't even migrate the template blueprints in this step).

But enabling the plugin without using it may be the reason why is not failing.

Our current solution is to try to disable Agora modules and everything when compiling the server. But we hope that you can guide us or give us a reference.
Thank you for your help!.

**Comment by oneSitDown** [comment]
你是aws 的windows服务器吗？我们没有在服务器上尝试部署过。我们sdk目前只支持windows，不支持linux。不过我认为在windows上部署不会用问题，因为windows机器本地是能够运行的。

**Comment by oneSitDown** [comment]
And if the windows server crashes, you can grab a windows dump and send it to us. My email is [wangxidong@agora.io](mailto:wangxidong@agora.io), you can send the dump to us, and we will pay attention to this issue.
