### ISSUE TITLE
Generate agora tokens

### ISSUE THREAD

**Issue by davidherran** [AgoraIO-Extensions/Agora-Unreal-RTC-SDK#41]
Do you have any knowledge or code about creating Agora tokens through unreal? 
We have to dynamically create them, because we need to have different channels. 

I see some code in the documentation like this: 
static std::string BuildTokenWithUid(
       const std::string& app_id,
       const std::string& app_certificate,
       const std::string& channel_name,
       uint32_t uid,
       uint32_t token_expire,
       uint32_t join_channel_privilege_expire = 0,
       uint32_t pub_audio_privilege_expire = 0,
       uint32_t pub_video_privilege_expire = 0,
       uint32_t pub_data_stream_privilege_expire = 0);

But I'm not sure about the implementation inside Unreal.

The idea is that at least 4 clients can share their screen and the other users have to be able to join to only one of them, like having multiple conferences.

So one of my concerns is about how the users are gonna get the right token.

If it's necessary I can use graphQL to send the token, so the most important part is how to generate it in unreal. 

Thanks in advance!

**Comment by oneSitDown** [comment]
**To generate tokens, please see this document https://docs.agora.io/en/live-streaming-premium-legacy/token_server?platform=Windows, we currently do not support creating tokens in sdk.** 
There is one more question, has the problem of creating LinuxSever AWS-Gamelift Failed build been solved? If there is a solution, can you reply to that issue? Make it clear to other users.

**Comment by davidherran** [comment]
We still having the problem about the linux server.

But is it possible to generate the token in the client? or what is the best way to do it?

I can implement something to store the tokens so the clients can get it, and we can create the tokens manually if necessary, but we are still lost about the way to generate them. 

Which tools or systems do we need to generate token? is it possible to do it in a normal computer deploying something? 
Our concern is that we need to set up a server or something.

Thank you for helping.

**Comment by oneSitDown** [comment]
We currently do not support systems with linux architecture, because there is no linux-related library in the current sdk. Have you tried windows server? Does it work on it? Also we are currently unable to create a token on the client.

**Comment by davidherran** [comment]
Yes, we have tried windows server, we had the same server process ending problem, but we are not sure if it's because of Agora.

But about the token stuff, we are just looking for a way to generate them. I see that I can do it with node.js running npm commands. Is that correct?

**Comment by oneSitDown** [comment]
Are you using tokens for security reasons? To use the token must be deployed on the server. If the token is to be generated on the client side, it is insecure, so generating a token makes no sense at all. Can you consider using appid without token. And if the windows server crashes, you can grab a windows dump and send it to us. My email is wangxidong@agora.io, you can send the dump to us, and we will pay attention to this issue.

**Comment by davidherran** [comment]
Oh yeah, we thought that the token was necessary, it worked, it only crash once.
So is perfectly working, thank you so much!!!!!!!!!!!
