### ISSUE TITLE
Compilation Errors

### ISSUE THREAD

**Issue by Shumaro211** [AgoraIO-Extensions/Agora-Unreal-RTC-SDK#43]
Hello there and thank you for your support. We were able to solve some problems about Agora by changing the plugin's type to "ClientOnly", but we are experiencing some similar errors in our plugins.
It's about dependencies; these plugins are not suppose to exist in the server, but we are using references to them, so these are the errors.
```
LogStreaming: Error: Couldn't find file for package /Script/AgoraExample requested by async loading code. NameToLoad: /Script/AgoraExample
[2022.10.01-14.28.29:338][  0]LogStreaming: Error: Found 1 dependent packages...
[2022.10.01-14.28.29:338][  0]LogStreaming: Error:   /Game/API-Example/HUD2/BP_HUD_Origin 
```
We have tried to add the plugin's content as additional directories to cook and ignore that content, but nothing changes.
And some of the references are the parent class of our main character, in case of agora, part of the HUD class for all the UI.

We have some other problems but I think is because of the same, like these:
```
LogStreaming: Error: **DumpDependencies [Dependencies]:
[2022.10.01-14.28.29:437][  0]LogStreaming: Error:     Export 27 /Game/API-Example/Advance/ScreenShare/BP_ScreenShare.BP_ScreenShare_C
```

**Comment by oneSitDown** [comment]
Sorry, China is on holiday now, and there will be a seven-day holiday for National Day. So I may not support very fast at the moment, please forgive me. I think your question can be similar to
https://forums.unrealengine.com/t/android-logstreaming-error/401453，please try it
