### ISSUE TITLE
Close microphone

### ISSUE THREAD

**Issue by Shumaro211** [AgoraIO-Extensions/Agora-Unreal-RTC-SDK#44]
Hello and thank you so much for your help.
Is there a way to mute your own microphone while using agora trough unreal? for voice and streaming channels

I'm using the c++ version, I saw that the RtcEngine has a method called "muteLocalAudioStream" and "muteLocalVideoStream", are these what I need to mute the audio?

**Comment by oneSitDown** [comment]
You're right. You can call this if you want to temporarily close the send stream. If you want to permanently close the stream when you join the room, you can do as I did below.
![image](https://user-images.githubusercontent.com/47908151/193962390-fab09285-2885-407f-b108-e42b927fbcda.png)
