### ISSUE TITLE
Assertion error: when adding new UI element inside OnUserJoinedCallback

### ISSUE THREAD

**Issue by Vicky-mSocial** [AgoraIO-Extensions/Agora-Unreal-RTC-SDK#45]
[log.txt](https://github.com/AgoraIO-Extensions/Agora-Unreal-RTC-SDK/files/9714214/log.txt)
![image](https://user-images.githubusercontent.com/113271868/194021515-d43285c0-a3b4-4536-8984-7ae4ccd43a7a.png)

I was trying to dynamically add Image components when new user joins, when I create the new widget there is no issues, but as i add it to an existing widget as a child, it is causing an assertion error. 

I am using agora blueprint SDK and extending your blueprint example project

I see the issue is due to adding widget in a non-game thread but cannot find a solution for it. Is there a way that you suggest through blueprint that i can create widgets dynamically based on number of users joining

**Comment by oneSitDown** [comment]
can you give me you blueprint line？I dont know you how to do it

**Comment by Vicky-mSocial** [comment]
![image](https://user-images.githubusercontent.com/113271868/194048552-56c1f92a-a488-4530-aaea-f96d5b31776d.png)
![image](https://user-images.githubusercontent.com/113271868/194048721-a4efd88e-ba32-4f38-add9-bf5ee6fe73e7.png)
![image](https://user-images.githubusercontent.com/113271868/194048825-2751cd3a-5278-437d-94b0-204f615c55cd.png)
![image](https://user-images.githubusercontent.com/113271868/194049009-d9115711-2ad7-48ce-b7fb-9ca3f36e93e0.png)
![image](https://user-images.githubusercontent.com/113271868/194049183-1314faa8-853e-4a2a-9979-7c1d8f5bb932.png)
![image](https://user-images.githubusercontent.com/113271868/194049257-d04ba6db-015f-496e-b784-9957352bed6a.png)
Error is gone if I disconnect that last node.

**Comment by oneSitDown** [comment]
I think that some child should be created when initializing, and the child should be hung on the parent object, not created when user joining，Show and hide these chidl when you want to use it。

**Comment by Vicky-mSocial** [comment]
I can solve it that way, would have been nice if we can deal with it more dynamically than hard coding that way.

**Comment by Vicky-mSocial** [comment]
It works, Thank you @oneSitDown . I should have tried that, thank you for such a fast support

**Comment by oneSitDown** [comment]
> It works, Thank you @oneSitDown . I should have tried that, thank you for such a fast support


Please let us know if it works, we will fix this issue in a subsequent update
