### ISSUE TITLE
Duplicated audio

### ISSUE THREAD

**Issue by Shumaro211** [AgoraIO-Extensions/Agora-Unreal-RTC-SDK#47]
**Can you please tell me how can I disable or don't enable the audio for the screen sharing?**

I have my audio duplicated because of using the screen share audio and a normal audio channel.
I tried with some functions but is not working or is crashing.

I remember that you told me to do something if it was crashing, is happening a lot.

**Comment by oneSitDown** [comment]
If you are using an Android device
![image](https://user-images.githubusercontent.com/47908151/195116975-a830764d-ecd1-4ce9-8325-bcc66d7aac10.png)
set this value false
f you don't want to hear from the far end, you can try this
![image](https://user-images.githubusercontent.com/47908151/195117316-f8224d62-1b3a-4325-8374-3aee36963551.png)
set this value to false

**Comment by Shumaro211** [comment]
Thank you!

**Comment by Shumaro211** [comment]
Sorry, but I set all the audio functions to false and I can still hear myself, I mean the screen share audio.
![image](https://user-images.githubusercontent.com/66711189/197536833-5da6d5de-fc1a-48ab-87ea-a87ac1c00fc9.png)

**Comment by oneSitDown** [comment]
![image](https://user-images.githubusercontent.com/47908151/197665732-5f74702a-66fd-4c49-8674-37155d08489a.png)

**Comment by oneSitDown** [comment]
https://docs.unrealengine.com/4.27/en-US/ProductionPipelines/CloudDeployments/AWS/
Are you using this tutorial to deploy the aws service?

**Comment by Shumaro211** [comment]
No, but is similar, we are using a template to connect to all the AWS, is called "Multiplayer With Blueprints"

**Comment by oneSitDown** [comment]
ok, did you try it with my code?

**Comment by oneSitDown** [comment]
and I don't know anything about aws server at the moment, I'll have to spend time researching this bug

**Comment by Shumaro211** [comment]
We have decided to use our own machine as a dedicated server. Probably we are going to discuss that with your customer support, but yeah, AWS is a common solution for hosting games and platforms.
So I would recomment Agora to find solutions for Unreal, they recommended us to use Unity.

**Comment by oneSitDown** [comment]
Yes, because Unity is indeed an easier game engine to master these days, and our customer support has no knowledge of unreal at all, so they would recommend Unity. Also, can you give me a tutorial on aws server? It is best to teach at the nanny level, starting from registering an account. this is important to me.

**Comment by Shumaro211** [comment]
I like this one: https://www.youtube.com/watch?v=tOy0xYaP3wA
But as I said, we are using a plugin, they have their own tutorials, is this one: https://www.unrealengine.com/marketplace/en-US/product/aws-cognito-dynamodb-gamelift-lambda?sessionInvalidated=true

**Comment by Shumaro211** [comment]
I did it, I can still hear myself

**Comment by Shumaro211** [comment]
![image](https://user-images.githubusercontent.com/66711189/197796599-d9758a21-83c2-426f-bd70-8594a8d78265.png)
What I'm doing is to put a 3d widget that connects to the channel I'm sharing, but I wanna use an alternative channel audio instead, mainly because I hear myself.

**Comment by Shumaro211** [comment]
I don't wanna enable the audio when using the screen share widget, my mic audio.
I just wanna share the video.

**Comment by oneSitDown** [comment]
Sorry, I'm off work now. I'll fix this at work tomorrow.

**Comment by oneSitDown** [comment]
are you try rtcengine->disableaudio？

**Comment by oneSitDown** [comment]
https://github.com/AgoraIO-Extensions/Agora-Unreal-RTC-SDK/blob/main/Agora-Unreal-SDK-CPP-Example/Source/AgoraExample/JoinMultipleChannelWidget.cpp

**Comment by Shumaro211** [comment]
Cool, is working. Thank you!!
