### ISSUE TITLE
3D Audio

### ISSUE THREAD

**Issue by Shumaro211** [AgoraIO-Extensions/Agora-Unreal-RTC-SDK#48]
I would like to let you know that we successfully presented a demo of our metaverse using Agora, the project is getting bigger.

We are in contact with your customer support and they told us that the SDK 4.0 was release so we can start working with the 3D Audio, which is the feature that we want to use for the next release.

I see that you have something called "Spatial Audio" but not sure how it works; if that's similar to and audio 3d or if you are gonna have something else or what we can do to have this feature.

**Comment by oneSitDown** [comment]
You can see a demo called spatialaudio, you can try it, you plug in the headphones and enter the demo. Then another client enters the room. Click left or right. You can hear the sound from the left or right earphone. Thanks for your use. Please click star if possible, it's important to me.

**Comment by Shumaro211** [comment]
How do I click the star?
We tried that but it was not working, I'm gonna try again.
I guess I can use maths to simulate the effect into a 3d space, but do you have any considerations or planning something to get that to work in a 3d space?

**Comment by oneSitDown** [comment]
It can work in 3d space, you only need to pass the vector3 of the object to convert it into a float array to the sdk, this part may be calculated by yourself. And the star I said refers to the github star and not elsewhere

**Comment by Shumaro211** [comment]
Oh now I remember the issue with the spatial audio. I could not get it to work.
I can only hear the voice if I join to a normal audio channel.
If I try to join using the spatial audio interface is not working. How is this suppose to work? 
![image](https://user-images.githubusercontent.com/66711189/195952428-0ac6c657-0ffd-46cd-aea4-50e14ce3591c.png)

**Comment by oneSitDown** [comment]
èngcháng de?
Do you mean that two sections, one section is a spatial sound effect demo, and the other is a normal call can have spatial sound effects? And if both segments are spatial sound demos, won't it work? Also, I saw the picture you shared and it seems that the uid at both ends are the same. Are you sure it is normal?

**Comment by oneSitDown** [comment]
èngcháng de?
Do you mean that two sections, one section is a spatial sound effect demo, and the other is a normal call can have spatial sound effects? And if both segments are spatial sound demos, won't it work? Also, I saw the picture you shared and it seems that the uid at both ends are the same. Are you sure it is normal?

**Comment by oneSitDown** [comment]
You can try this function with headphones

**Comment by Shumaro211** [comment]
Yeah, I'm using headphones.
What I wanna say is that I can't hear anything if I try to join using the spatial audio. I can only hear the other person if he join to a normal call, because of using the same channel..
So I don't know what do I need to do to get the spatial audio working.

**Comment by oneSitDown** [comment]
![image](https://user-images.githubusercontent.com/47908151/195962078-330f0474-74ed-4449-875a-906685b78667.png)
sorry,you can add this code to fix this bug，we will fix next version

**Comment by Shumaro211** [comment]
Cool, it was working
