### ISSUE TITLE
Dynamic Channel Created By Users At Runtime

### ISSUE THREAD

**Issue by WalidCHEKKOURI** [AgoraIO-Extensions/Agora-Unreal-RTC-SDK#50]
In the Agora website it's stated that users can create their own channels at runtime that other users can join, can this currently be done with Unreal too?
In this link there is no UE example: https://www.agora.io/en/developer-resources/advanced-guides-dynamic-channel/

If yes, is there any documentation on how to approach it please?

Thanks.

**Comment by oneSitDown** [comment]
Sorry, currently our unreal does not have the function of rtm for the time being. We will support this demo in the future.
