### ISSUE TITLE
Errors in build

### ISSUE THREAD

**Issue by Shumaro211** [AgoraIO-Extensions/Agora-Unreal-RTC-SDK#51]
Hello there.
I'm having these errors, I just copied the source from another project, I have the plugin enabled and I created a module to add agora.
![image](https://user-images.githubusercontent.com/66711189/197360233-6e278434-dd41-4ae3-a6e9-da3ad40e6ea4.png)
Some of the errors seems to be syntax errors.

**Comment by oneSitDown** [comment]
Did you create a new project and then import the plugin? I think there may be a problem with your import method. Can you download one from release again and import it? Or you tell me what platform packaging error is. I can try to reproduce it.

**Comment by oneSitDown** [comment]
this error like plugin version is not right.

**Comment by Shumaro211** [comment]
I copied from another project, but I had the same kind of errors using a new one, some times I have them while compiling the project.
I'm building for Linux Server.
Well Is working on another project.
I would say that is because of the project or like you say, copy the plugin, but those syntax errors are weird.

**Comment by oneSitDown** [comment]
We do not currently support the linux architecture. If you just want to compile and pass, you can add/remove the linux macro to the error code to make the compilation pass.

**Comment by oneSitDown** [comment]
Please notify our SA if you want us to be this architecture this time. We will collect suggestions and may support this architecture in the future.

**Comment by Shumaro211** [comment]
Oh yeah sorry, I could sove the problems by not loading the agora module in the server, I also tried with windows, but the fleet is also crashing, I'm trying to find the reason.
Can you explain me more about how to do that macro thing so I can try to implement it?

**Comment by oneSitDown** [comment]
It is already 12 o'clock on our side on Sunday night, and I may have to wait until I go to work at 10 o'clock in the morning to help give specific code examples. It seems that the example is only wrongly compiled, you can comment out the code corresponding to the number of lines to ensure that the compilation passes.

**Comment by Shumaro211** [comment]
Well I have those errors in my copy of the project, but for now I have another stable copy so let's just skip this please.
