### ISSUE TITLE
Crash on Windows AWS

### ISSUE THREAD

**Issue by Shumaro211** [AgoraIO-Extensions/Agora-Unreal-RTC-SDK#52]
Hello there. We have been suffering for weeks with Agora so please help us with this. 
We are using AWS Gamelift, we have tried with a Linux Server mostly, I know that is not compatible, we tried to disable agora as much as possible, **but we have tried also with Windows having the same results**
The server crash as long as we implement the Agora classes as a module, even withotu using it. The server build is running when excecuting it locally, but in gamelift is crashing:

Server process exited without calling ProcessEnding(), exitCode(-1073741515), launchPath(C:\game\OriginWorlds\Binaries\Win64\OriginWorldsServer.exe), arguments(-port=7777), instanceId(i-04e44ac2f787ecb5a), publicIP(3.89.117.246), gameSessionId(none)

**Comment by oneSitDown** [comment]
I want to help you too, but we don't have an environment on our side to reproduce this problem. Our department does not rent aws servers. I haven't tried it on the server either.
