### ISSUE TITLE
Bug crash with wrong format API key when leaving

### ISSUE THREAD

**Issue by hcabel** [AgoraIO-Extensions/Agora-Unreal-RTC-SDK#53]
hello, I think I found bug.

**Bug:**
Crash when leaving any kind of channel or when stopping the play mode after entering a sessiom.

**Fix:**
The crash went away after I subscribe to the free subscription.

**Spec:**
I tried with the Bp and Cpp exemple on both Unreal Engine 5/4.27, and on a windows x64 computer.
With the v4.0.0.5-alpha.1 of the [agora.io](http://agora.io/) SDK.
https://github.com/AgoraIO-Extensions/Agora-Unreal-RTC-SDK/releases/tag/v4.0.0.5-alpha.1

**How to reproduce:**
1- Create a new account and create a project.
2- Start the CPP example in the editor (play mode)
3- Fill the api key
4- add a channel name
5- Join the audio channel
6- either stop the play or click on the return button

(Edit)
In fact it is not fixed because of the subscription.
It's still crashing when using the APP ID in the 'project management' panel of the console.
But if I used the APP ID in the Overview panel of the console (it's a different string BTW) it's not crashing anymore.
There both call APP ID and there for the same project but there not formated the same way;
Crashing string format is using: lower/upper letters, numbers and symbols (at least the '#' symbols) for a length of 16 char.
Not crashing String fromat is using: lower/upper letters and number for a length of 32 char. (edited)

**Comment by oneSitDown** [comment]
thank you very much

**Comment by oneSitDown** [comment]
Do you mean the crash caused by different appid formats copied from different places?

**Comment by hcabel** [comment]
Yes for some reason I got 2 ID for the same project.

**One here in the console overview:**
![image](https://user-images.githubusercontent.com/49307497/197898683-1b9a6728-f08a-4149-a8e7-4603a32c1df6.png)
**And one here in the project management section:** (the second icon on the left side bar)
![image](https://user-images.githubusercontent.com/49307497/197898847-abb28adb-60d5-46c5-8a1c-f1c22bfe7913.png)

And both of those App UD are for the same project and should be the same. (has I understand it)<br/>
But those IDs were not just different keys, they also had a different format, the second APP ID (the one who was causing the crash) had special chars in it and were half of the size.

I just notice while making those screenshots that the bug is no more :D
Anyhow I guess it would be a nice touch to check the format key to see if it's the right length and using only char and numbers.

**Comment by oneSitDown** [comment]
don't think this should be a bug on the official website. I tested this problem in my development branch and it did not reproduce. Can you go to my development branch dev/xidongarrange and test this problem?

**Comment by hcabel** [comment]
Yeah probably, I first I though it was a problem with unreal since I saw the 'APP ID' label and it was crashing, but yeah then I figure out it  cam from the 'APP ID' key who was not right.

I'll try, I guess you just have to put a random string of 32 char with special char and when ending the play game or clicking on the back button should trigger the crash.

**Comment by oneSitDown** [comment]
Can you give me an example of special characters? I would like a concrete example of reproduction to test.

**Comment by hcabel** [comment]
Yeah sure, in my there was multiple '#':
something like this:
cdc7a#PioxQcnbFgbM#m3DS77E#7FNas

**Comment by hcabel** [comment]
So I tried not on your branch but on the release using the key that I gave you and it work (BTW I didn't use any token)

I got:
Exception has occurred: W32/0xC0000005
Unhandled exception thrown: read access violation.
this->MediaProxy._Mypair._Myval2 was nullptr.

in this location: RtcEngineProxy.cpp:49

**Comment by oneSitDown** [comment]
![image](https://user-images.githubusercontent.com/47908151/197930419-68246f39-1375-4bf1-a5a2-5e2fbec1104f.png)
My latest version of the sdk code is this, this will be iterated in the next version, can you check it?

**Comment by hcabel** [comment]
Yes it did prevent Unreal from crashing
