### ISSUE TITLE
Could Not Find AgoraScreenShareExtension Android Build Error

### ISSUE THREAD

**Issue by WalidCHEKKOURI** [AgoraIO-Extensions/Agora-Unreal-RTC-SDK#56]
When building for android in Unreal Engine 5.0.3 for distribution I get this error in the output log:

> FAILURE: Build failed with an exception.
> UATHelper: Packaging (Android (ASTC)): * What went wrong:
> UATHelper: Packaging (Android (ASTC)): Could not determine the dependencies of task ':app:compileReleaseJavaWithJavac'.
> UATHelper: Packaging (Android (ASTC)): > Could not resolve all task dependencies for configuration ':app:releaseCompileClasspath'.
> UATHelper: Packaging (Android (ASTC)):    > Could not find :AgoraScreenShareExtension:.
> UATHelper: Packaging (Android (ASTC)):      Required by:
> UATHelper: Packaging (Android (ASTC)):          project :app

Did I miss something?

**Comment by oneSitDown** [comment]
> Here is a screenshot of the Build.cs of the Agora plugin, I'm still not sure why I keep getting the error when building for shipping though! <img alt="image" width="1047" src="https://user-images.githubusercontent.com/11277981/200162533-954661a6-9842-471a-aaf5-f266137cbf0a.png">

package in debug is not error？

**Comment by WalidCHEKKOURI** [comment]
> ![image](https://user-images.githubusercontent.com/47908151/200161714-d018b5cb-5804-454d-851e-9248711321f4.png) can you find this file in path？

When packaging for debug/development I get no error @oneSitDown , is there something I need to configure for distribution version?

**Comment by oneSitDown** [comment]
> shipping

sorry ，we do not test shipping，why are you build must shipping ?

**Comment by WalidCHEKKOURI** [comment]
> > shipping
> 
> sorry ，we do not test shipping，why are you build must shipping ?

Our project hopefully will soon be shipped & we wanted to make sure that everything works well in the shipping version, doesn't Agora work in shipping version?!

**Comment by oneSitDown** [comment]
> > > shipping
> > 
> > 
> > sorry ，we do not test shipping，why are you build must shipping ?
> 
> Our project hopefully will soon be shipped & we wanted to make sure that everything works well in the shipping version, doesn't Agora work in shipping version?!

No, we haven't tested the shapping on the Android platform, we will test it tomorrow and give you an answer. May I?

**Comment by WalidCHEKKOURI** [comment]
> > > > shipping
> > > 
> > > 
> > > sorry ，we do not test shipping，why are you build must shipping ?
> > 
> > 
> > Our project hopefully will soon be shipped & we wanted to make sure that everything works well in the shipping version, doesn't Agora work in shipping version?!
> 
> No, we haven't tested the shapping on the Android platform, we will test it tomorrow and give you an answer. May I?

Yes please, we would highly appreciate that @oneSitDown since this is very important for our project progress, I look forward to hearing back from you

**Comment by oneSitDown** [comment]
![image](https://user-images.githubusercontent.com/47908151/200161714-d018b5cb-5804-454d-851e-9248711321f4.png)
can you find this file in path？

**Comment by WalidCHEKKOURI** [comment]
Yes it's already there @oneSitDown :
<img width="386" alt="image" src="https://user-images.githubusercontent.com/11277981/200161991-e68528cb-8db1-4a3d-9ec1-feaec79879d7.png">

**Comment by oneSitDown** [comment]
> > > > > shipping
> > > > 
> > > > 
> > > > sorry ，we do not test shipping，why are you build must shipping ?
> > > 
> > > 
> > > Our project hopefully will soon be shipped & we wanted to make sure that everything works well in the shipping version, doesn't Agora work in shipping version?!
> > 
> > 
> > No, we haven't tested the shapping on the Android platform, we will test it tomorrow and give you an answer. May I?
> 
> Yes please, we would highly appreciate that @oneSitDown since this is very important for our project progress, I look forward to hearing back from you
![image](https://user-images.githubusercontent.com/47908151/200164597-ee7256b6-63bd-476d-9fad-d933473cdedc.png)
If you don't need screen sharing on Android, you can comment out this line of code and you can package it. We'll investigate the cause of this later

**Comment by oneSitDown** [comment]
We tested it in versions 4.27 and 5.0.2. There is no problem with packaging the shapping in version 4.27, but 5.0.2 can indeed reproduce your problem.

**Comment by oneSitDown** [comment]
[APL_armv7Template.zip](https://github.com/AgoraIO-Extensions/Agora-Unreal-RTC-SDK/files/9945711/APL_armv7Template.zip)
We fixed this problem, just replace the file in the path.
![image](https://user-images.githubusercontent.com/47908151/200168062-d53be49c-0687-4f05-ba85-af982fb8dffe.png)

**Comment by WalidCHEKKOURI** [comment]
> [APL_armv7Template.zip](https://github.com/AgoraIO-Extensions/Agora-Unreal-RTC-SDK/files/9945711/APL_armv7Template.zip) We fixed this problem, just replace the file in the path. ![image](https://user-images.githubusercontent.com/47908151/200168062-d53be49c-0687-4f05-ba85-af982fb8dffe.png) this bug we will push to master next version

Thanks @oneSitDown the shipping version compiles without errors now, we certainly appreciate the support and the quick fix :)
