### ISSUE TITLE
WebCamera opening

### ISSUE THREAD

**Issue by Shumaro211** [AgoraIO-Extensions/Agora-Unreal-RTC-SDK#57]
Hello there. 
When I excecute the game, I guess that because of the device manager functionality, the device's camera turns on. We want to avoid that. 
I can't find something related specifically to the cameras, how can I avoid that?
Thank you in advance.

**Comment by oneSitDown** [comment]
![image](https://user-images.githubusercontent.com/47908151/200983606-e392b038-6cc0-46b9-bc75-55b3780c16eb.png)
this code file open camera，you can delete it.

**Comment by Shumaro211** [comment]
Thank you
