### ISSUE TITLE
Building for AWS Linux Server

### ISSUE THREAD

**Issue by YousefBadr** [AgoraIO-Extensions/Agora-Unreal-RTC-SDK#58]
I'm currently using AWS multiplayer system. when I tried to build for Linux server I get the errors below: 
`PackagingResults: Error: undefined symbol: getMediaPlayerCacheManager
PackagingResults: Error: undefined symbol: createAgoraRtcEngine
PackagingResults: Error: linker command failed with exit code 1 (use -v to see invocation)
PackagingResults: Error: undefined symbol: getMediaPlayerCacheManager
PackagingResults: Error: undefined symbol: createAgoraRtcEngine
PackagingResults: Error: linker command failed with exit code 1 (use -v to see invocation)
PackagingResults: Error: undefined symbol: getMediaPlayerCacheManager
PackagingResults: Error: undefined symbol: createAgoraRtcEngine
PackagingResults: Error: linker command failed with exit code 1 (use -v to see invocation)
PackagingResults: Error: undefined symbol: getMediaPlayerCacheManager
PackagingResults: Error: undefined symbol: createAgoraRtcEngine
PackagingResults: Error: linker command failed with exit code 1 (use -v to see invocation)
PackagingResults: Error: undefined symbol: getMediaPlayerCacheManager
PackagingResults: Error: undefined symbol: createAgoraRtcEngine
PackagingResults: Error: linker command failed with exit code 1 (use -v to see invocation)
PackagingResults: Error: undefined symbol: getMediaPlayerCacheManager
PackagingResults: Error: undefined symbol: createAgoraRtcEngine
PackagingResults: Error: linker command failed with exit code 1 (use -v to see invocation)
PackagingResults: Error: undefined symbol: getMediaPlayerCacheManager
PackagingResults: Error: undefined symbol: createAgoraRtcEngine
PackagingResults: Error: linker command failed with exit code 1 (use -v to see invocation)
PackagingResults: Error: undefined symbol: getMediaPlayerCacheManager
PackagingResults: Error: undefined symbol: createAgoraRtcEngine
PackagingResults: Error: linker command failed with exit code 1 (use -v to see invocation)
PackagingResults: Error: undefined symbol: getMediaPlayerCacheManager
PackagingResults: Error: undefined symbol: createAgoraRtcEngine
PackagingResults: Error: linker command failed with exit code 1 (use -v to see invocation)
PackagingResults: Error: undefined symbol: getMediaPlayerCacheManager
PackagingResults: Error: undefined symbol: createAgoraRtcEngine
PackagingResults: Error: linker command failed with exit code 1 (use -v to see invocation)
UATHelper: Packaging (Linux): Took 205.7304116s to run UnrealBuildTool.exe, ExitCode=6
UATHelper: Packaging (Linux): UnrealBuildTool failed. See log for more details. (C:\UnrealEngine5\UnrealEngine-5.0.3-release\Engine\Programs\AutomationTool\Saved\Logs\UBT-ShoppingMallServer-Linux-Development.txt)
UATHelper: Packaging (Linux): AutomationTool executed for 0h 3m 31s
UATHelper: Packaging (Linux): AutomationTool exiting with ExitCode=6 (6)
UATHelper: Packaging (Linux): BUILD FAILED
PackagingResults: Error: Unknown Error`

I know the plugin doesn't support Linux but when I tried to disable it in Linux server build only, blueprints that depend on the plugin failed to run on server. How Can I solve it on Linux?

**Comment by oneSitDown** [comment]
![image](https://user-images.githubusercontent.com/47908151/201573210-84d33fa8-909b-459c-bc80-70336ccb74c3.png)
![image](https://user-images.githubusercontent.com/47908151/201573586-d75f3397-2de4-41bc-b6d0-f50962cfc140.png)
![image](https://user-images.githubusercontent.com/47908151/201573599-92801282-ea92-417d-ac41-f4ed0e70857d.png)
it seem like C Api error，you can add this code to fix this bug

**Comment by YousefBadr** [comment]
I updated the code with the above screenshots and compiled again. Now I get these errors when try to package Linux server:
`UATHelper: Packaging (Linux): >>> referenced by AgoraMediaPlayer.cpp:328 (C:/Users/paperspace/Documents/Unreal Projects/ElegantroApp/Plugins/AgoraPlugin/Source/AgoraPlugin/Private/AgoraBluePrint\AgoraMediaPlayer.cpp:328)
UATHelper: Packaging (Linux): >>>               C:/Users/paperspace/Documents/Unreal Projects/ElegantroApp/Intermediate/Build/Linux/B4D820EA/ShoppingMallServer/Development/AgoraPlugin/AgoraMediaPlayer.cpp.o:(UIMediaPlayerCacheManager::RemoveCacheByUri(FString))
UATHelper: Packaging (Linux): >>> referenced 8 more times
UATHelper: Packaging (Linux): ld.lld: error: undefined symbol: createAgoraRtcEngine
UATHelper: Packaging (Linux): >>> referenced by RtcEngineProxy.cpp:36 (C:/Users/paperspace/Documents/Unreal Projects/ElegantroApp/Plugins/AgoraPlugin/Source/AgoraPlugin/Private\RtcEngineProxy.cpp:36)
UATHelper: Packaging (Linux): >>>               C:/Users/paperspace/Documents/Unreal Projects/ElegantroApp/Intermediate/Build/Linux/B4D820EA/ShoppingMallServer/Development/AgoraPlugin/RtcEngineProxy.cpp.o:(agora::rtc::ue::RtcEngineProxy::RtcEngineProxy())
UATHelper: Packaging (Linux): clang++: error: linker command failed with exit code 1 (use -v to see invocation)
UATHelper: Packaging (Linux): Failed to link C:\Users\paperspace\Documents\Unreal Projects\ElegantroApp\Binaries\Linux\ShoppingMallServer after 10 retries
PackagingResults: Error: undefined symbol: createAgoraRtcEngine
PackagingResults: Error: linker command failed with exit code 1 (use -v to see invocation)
PackagingResults: Error: undefined symbol: getMediaPlayerCacheManager
PackagingResults: Error: undefined symbol: createAgoraRtcEngine
PackagingResults: Error: linker command failed with exit code 1 (use -v to see invocation)
PackagingResults: Error: undefined symbol: getMediaPlayerCacheManager
PackagingResults: Error: undefined symbol: createAgoraRtcEngine
PackagingResults: Error: linker command failed with exit code 1 (use -v to see invocation)
PackagingResults: Error: undefined symbol: getMediaPlayerCacheManager
PackagingResults: Error: undefined symbol: createAgoraRtcEngine
PackagingResults: Error: linker command failed with exit code 1 (use -v to see invocation)`

**Comment by YousefBadr** [comment]
Sorry I didn't understand that. I've already added these lines. Do you mean that I should call RemoveAllCache in blueprint then try to package again ?

**Comment by YousefBadr** [comment]
![image](https://user-images.githubusercontent.com/45340990/201706050-a981bbab-e923-4a3c-873f-ff10459afde8.png)

I did that and still the same errors appear.
`PackagingResults: Error: undefined symbol: getMediaPlayerCacheManager
PackagingResults: Error: undefined symbol: createAgoraRtcEngine
PackagingResults: Error: linker command failed with exit code 1 (use -v to see invocation)
PackagingResults: Error: undefined symbol: getMediaPlayerCacheManager
PackagingResults: Error: undefined symbol: createAgoraRtcEngine
PackagingResults: Error: linker command failed with exit code 1 (use -v to see invocation)
PackagingResults: Error: undefined symbol: getMediaPlayerCacheManager
PackagingResults: Error: undefined symbol: createAgoraRtcEngine
PackagingResults: Error: linker command failed with exit code 1 (use -v to see invocation)
PackagingResults: Error: undefined symbol: getMediaPlayerCacheManager
PackagingResults: Error: undefined symbol: createAgoraRtcEngine
PackagingResults: Error: linker command failed with exit code 1 (use -v to see invocation)
PackagingResults: Error: undefined symbol: getMediaPlayerCacheManager
PackagingResults: Error: undefined symbol: createAgoraRtcEngine
PackagingResults: Error: linker command failed with exit code 1 (use -v to see invocation)
PackagingResults: Error: undefined symbol: getMediaPlayerCacheManager
PackagingResults: Error: undefined symbol: createAgoraRtcEngine
PackagingResults: Error: linker command failed with exit code 1 (use -v to see invocation)
PackagingResults: Error: undefined symbol: getMediaPlayerCacheManager
PackagingResults: Error: undefined symbol: createAgoraRtcEngine
PackagingResults: Error: linker command failed with exit code 1 (use -v to see invocation)
PackagingResults: Error: undefined symbol: getMediaPlayerCacheManager
PackagingResults: Error: undefined symbol: createAgoraRtcEngine
PackagingResults: Error: linker command failed with exit code 1 (use -v to see invocation)
PackagingResults: Error: undefined symbol: getMediaPlayerCacheManager
PackagingResults: Error: undefined symbol: createAgoraRtcEngine
PackagingResults: Error: linker command failed with exit code 1 (use -v to see invocation)
PackagingResults: Error: undefined symbol: getMediaPlayerCacheManager
PackagingResults: Error: undefined symbol: createAgoraRtcEngine
PackagingResults: Error: linker command failed with exit code 1 (use -v to see invocation)
`

**Comment by oneSitDown** [comment]
yes，try to delete it.The best way is probably to find these two sentences of capi code and delete it. May be able to compile.or wait use add linux plugin future.I dont have linux pc to fix this bug now！sorry

**Comment by YousefBadr** [comment]
Ok, Thanks. I'll wait for the Linux support.
