### ISSUE TITLE
Close Distance Audio Call Loud volume issue

### ISSUE THREAD

**Issue by WalidCHEKKOURI** [AgoraIO-Extensions/Agora-Unreal-RTC-SDK#60]
I don't think this issue is particular to Agora since I tested calling a friend who is a few meters across from me and we noticed a high pitch audio that keeps increasing until it gets unbearable. 

This was the case when I decided today to show a demo to a friend and the audio call was so loud, I tried to have the volume at 0 on the device I'm running the demo on which is Quest 2 but I was still hearing the loud noise so I had to quit the app.

I think we won't have this issue when having distant calls but I'll have to test first to be certain, what do you think causes such issue? Are there any fixes we can introduce?
Thanks!

**Comment by oneSitDown** [comment]
This problem cannot be solved, and the reason for this is called feedback. We recommend that if two devices are used in close proximity, you can mute one device and use headphones to answer the other device to reduce the occurrence of this problem.

**Comment by WalidCHEKKOURI** [comment]
Got it, thanks again for your answer @oneSitDown.
