### ISSUE TITLE
Linux build failed!

### ISSUE THREAD

**Issue by skunnummal** [AgoraIO-Extensions/Agora-Unreal-RTC-SDK#61]
Hi,
I want to make a Linux build, but unfortunately, it's throwing the following error
**UATHelper: Packaging (Linux): ld.lld: error: undefined symbol: getMediaPlayerCacheManager**
 referenced by AgoraMediaPlayer.cpp:317 (<PROJECT>\Plugins\AgoraPlugin\Source\AgoraPlugin\Private\AgoraBluePrint\AgoraMediaPlayer.cpp:317)
**UATHelper: Packaging (Linux): ld.lld: error: undefined symbol: createAgoraRtcEngine**

Do we have support for Linux?
Can we make it work?

**Comment by oneSitDown** [comment]
Sorry, we currently don't have a library for linux. And there are currently no plans to support linux libraries. I'll tell our product manager. This feature may be supported in the future.
