### ISSUE TITLE
 a short build instruction would be desirable

### ISSUE THREAD

**Issue by Aeddon** [AgoraIO-Extensions/Agora-Unreal-RTC-SDK#63]
I downloaded 1.0.0 beta, but failed to build any of the examples and even the plugin.

It is not clear at all how to build these, a short howto would help

**Comment by oneSitDown** [comment]
Please read the readme here. 
https://github.com/AgoraIO-Extensions/Agora-Unreal-RTC-SDK/tree/main/Agora-Unreal-SDK-CPP-Example
Here's how to use.
