### ISSUE TITLE
Video Widget

### ISSUE THREAD

**Issue by Shumaro211** [AgoraIO-Extensions/Agora-Unreal-RTC-SDK#65]
Hello, please help me editing the "join channel video" widget.

Pretty much I just need to use the channel video widget to share the screen, no audio or camera's video.

To disable the camera video, I asked you for that, but the fix you sent me for the device manager's class is not affecting, I still see my own and all my customers cameras.
And I'd like to disable the audio for this video widget, if it's possible, that can keep my behavior.

Thank you so much for helping, this is the last thing we need.

**Comment by Shumaro211** [comment]
![image](https://user-images.githubusercontent.com/66711189/212174566-f5485aa3-3a52-4e46-8387-ccc9b6c42920.png)
I found this and I think is working

**Comment by oneSitDown** [comment]
you can use disableaudio

**Comment by Shumaro211** [comment]
can you please explain me what is that and how?

**Comment by Shumaro211** [comment]
okay I think I could disable the audio, but what about the camera? can I disable it?
