### ISSUE TITLE
Can not hear Sounds When Screen sharing on Windows Platform

### ISSUE THREAD

**Issue by Enzeun** [AgoraIO-Extensions/Agora-Unreal-RTC-SDK#66]
Hello, I'm developer in south Korea and i'm now developing screen sharing project

First of all, I apologize for my poor English.

I'm now using blueprints,
I have a problem in sharing device's sound when using screen share in 'windows' device.(I played youtube video using chrome and captured chrome site) 
I set Publish Screen Capture Video And Audio True value but it has no change,
How to share computer shounds? 

please help me

**Comment by Shumaro211** [comment]
Hello there, I'm not from Agora's team, but I think that is not part of the features, and in my experience platforms such as discord or zoom doesn't share the computers audio.

I barely know the code and I don't remember anything to try to manage that.

**Comment by oneSitDown** [comment]
you should use enableLoopbackRecording or enableLoopbackRecordingEx

**Comment by oneSitDown** [comment]
If you want to use this api on mac, you must install a virtual sound card

**Comment by oneSitDown** [comment]
@Enzeun

**Comment by Enzeun** [comment]
Thank you :)
