### ISSUE TITLE
Avoid Screen Share Overwrite

### ISSUE THREAD

**Issue by Shumaro211** [AgoraIO-Extensions/Agora-Unreal-RTC-SDK#68]
Hello there, is there a way to avoid someone overwriting the screen when 2 people try to share screen in the same channel?

I was about to manage that using my own backend, but if I can get if someone is sharing the screen in that channel directly from agora is great.

I only want to have one person sharing the screen per channel, not everyone should do that.

Thanks again for helping.

**Comment by oneSitDown** [comment]
Our official recommendation is that you can hardcode a screen sharing user id. Then other users only use this user id to judge whether to accept the screen sharing stream.

**Comment by Shumaro211** [comment]
Okay, It would be great to at least know if someone is sharing their screen from calling Agora.
I'll make my own backend, thanks for the suggestion.
