### ISSUE TITLE
App crashes on startup when compiling with "For distribution"

### ISSUE THREAD

**Issue by SarunasRamonas** [AgoraIO-Extensions/Agora-Unreal-RTC-SDK#69]
Hello, we are getting crashes every time we open the app, we are working with oculus Quest 1 & Quest 2, and previous builds with different Configurations as Client-Development or Client-Shipping are working, but since we activate "For distribution", we get this error:
[GameActivity] java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.Inlusion.Multiplayer-K9sNZgeAAVQqJ9t6tmzj6A==/base.apk"],nativeLibraryDirectories=[/data/app/com.Inlusion.Multiplayer-K9sNZgeAAVQqJ9t6tmzj6A==/lib/arm64, /data/app/com.Inlusion.Multiplayer-K9sNZgeAAVQqJ9t6tmzj6A==/base.apk!/lib/arm64-
v8a, /system/lib64, /system/product/lib64]]] couldn't find "liblibagora-fdkaac.so"
D/UE4     : [GameActivity] Failed to load libagora-fdkaac library
D/UE4     : [GameActivity] java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.Inlusion.Multiplayer-K9sNZgeAAVQqJ9t6tmzj6A==/base.apk"],nativeLibraryDirectories=[/data/app/com.Inlusion.Multiplayer-K9sNZgeAAVQqJ9t6tmzj6A==/lib/arm64, /data/app/com.Inlusion.Multiplayer-K9sNZgeAAVQqJ9t6tmzj6A==/base.apk!/lib/arm64-
v8a, /system/lib64, /system/product/lib64]]] couldn't find "liblibagora-ffmpeg.so"
D/UE4     : [GameActivity] Failed to load libagora-ffmpeg library
D/UE4     : [GameActivity] java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.Inlusion.Multiplayer-K9sNZgeAAVQqJ9t6tmzj6A==/base.apk"],nativeLibraryDirectories=[/data/app/com.Inlusion.Multiplayer-K9sNZgeAAVQqJ9t6tmzj6A==/lib/arm64, /data/app/com.Inlusion.Multiplayer-K9sNZgeAAVQqJ9t6tmzj6A==/base.apk!/lib/arm64-
v8a, /system/lib64, /system/product/lib64]]] couldn't find "liblibagora-rtc-sdk.so"
D/UE4     : [GameActivity] Failed to load libagora-rtc-sdk library
D/UE4     : [GameActivity] java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.Inlusion.Multiplayer-K9sNZgeAAVQqJ9t6tmzj6A==/base.apk"],nativeLibraryDirectories=[/data/app/com.Inlusion.Multiplayer-K9sNZgeAAVQqJ9t6tmzj6A==/lib/arm64, /data/app/com.Inlusion.Multiplayer-K9sNZgeAAVQqJ9t6tmzj6A==/base.apk!/lib/arm64-
v8a, /system/lib64, /system/product/lib64]]] couldn't find "liblibagora-soundtouch.so"
D/UE4     : [GameActivity] Failed to load libagora-soundtouch library
D/UE4     : [GameActivity] java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.Inlusion.Multiplayer-K9sNZgeAAVQqJ9t6tmzj6A==/base.apk"],nativeLibraryDirectories=[/data/app/com.Inlusion.Multiplayer-K9sNZgeAAVQqJ9t6tmzj6A==/lib/arm64, /data/app/com.Inlusion.Multiplayer-K9sNZgeAAVQqJ9t6tmzj6A==/base.apk!/lib/arm64-
v8a, /system/lib64, /system/product/lib64]]] couldn't find "liblibagora_ai_noise_suppression_extension.so"
D/UE4     : [GameActivity] Failed to load libagora_ai_noise_suppression_extension library
D/UE4     : [GameActivity] java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.Inlusion.Multiplayer-K9sNZgeAAVQqJ9t6tmzj6A==/base.apk"],nativeLibraryDirectories=[/data/app/com.Inlusion.Multiplayer-K9sNZgeAAVQqJ9t6tmzj6A==/lib/arm64, /data/app/com.Inlusion.Multiplayer-K9sNZgeAAVQqJ9t6tmzj6A==/base.apk!/lib/arm64-
v8a, /system/lib64, /system/product/lib64]]] couldn't find "liblibagora_audio_beauty_extension.so"
D/UE4     : [GameActivity] Failed to load libagora_audio_beauty_extension library
D/UE4     : [GameActivity] java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.Inlusion.Multiplayer-K9sNZgeAAVQqJ9t6tmzj6A==/base.apk"],nativeLibraryDirectories=[/data/app/com.Inlusion.Multiplayer-K9sNZgeAAVQqJ9t6tmzj6A==/lib/arm64, /data/app/com.Inlusion.Multiplayer-K9sNZgeAAVQqJ9t6tmzj6A==/base.apk!/lib/arm64-
v8a, /system/lib64, /system/product/lib64]]] couldn't find "liblibagora_clear_vision_extension.so"
D/UE4     : [GameActivity] Failed to load libagora_clear_vision_extension library
D/UE4     : [GameActivity] java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.Inlusion.Multiplayer-K9sNZgeAAVQqJ9t6tmzj6A==/base.apk"],nativeLibraryDirectories=[/data/app/com.Inlusion.Multiplayer-K9sNZgeAAVQqJ9t6tmzj6A==/lib/arm64, /data/app/com.Inlusion.Multiplayer-K9sNZgeAAVQqJ9t6tmzj6A==/base.apk!/lib/arm64-
v8a, /system/lib64, /system/product/lib64]]] couldn't find "liblibagora_content_inspect_extension.so"
D/UE4     : [GameActivity] Failed to load libagora_content_inspect_extension library
D/UE4     : [GameActivity] java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.Inlusion.Multiplayer-K9sNZgeAAVQqJ9t6tmzj6A==/base.apk"],nativeLibraryDirectories=[/data/app/com.Inlusion.Multiplayer-K9sNZgeAAVQqJ9t6tmzj6A==/lib/arm64, /data/app/com.Inlusion.Multiplayer-K9sNZgeAAVQqJ9t6tmzj6A==/base.apk!/lib/arm64-
v8a, /system/lib64, /system/product/lib64]]] couldn't find "liblibagora_dav1d.so"
D/UE4     : [GameActivity] Failed to load libagora_dav1d library
D/UE4     : [GameActivity] java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.Inlusion.Multiplayer-K9sNZgeAAVQqJ9t6tmzj6A==/base.apk"],nativeLibraryDirectories=[/data/app/com.Inlusion.Multiplayer-K9sNZgeAAVQqJ9t6tmzj6A==/lib/arm64, /data/app/com.Inlusion.Multiplayer-K9sNZgeAAVQqJ9t6tmzj6A==/base.apk!/lib/arm64-
v8a, /system/lib64, /system/product/lib64]]] couldn't find "liblibagora_pvc_extension.so"
D/UE4     : [GameActivity] Failed to load libagora_pvc_extension library
D/UE4     : [GameActivity] java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.Inlusion.Multiplayer-K9sNZgeAAVQqJ9t6tmzj6A==/base.apk"],nativeLibraryDirectories=[/data/app/com.Inlusion.Multiplayer-K9sNZgeAAVQqJ9t6tmzj6A==/lib/arm64, /data/app/com.Inlusion.Multiplayer-K9sNZgeAAVQqJ9t6tmzj6A==/base.apk!/lib/arm64-
v8a, /system/lib64, /system/product/lib64]]] couldn't find "liblibagora_screen_capture_extension.so"
D/UE4     : [GameActivity] Failed to load libagora_screen_capture_extension library
D/UE4     : [GameActivity] java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.Inlusion.Multiplayer-K9sNZgeAAVQqJ9t6tmzj6A==/base.apk"],nativeLibraryDirectories=[/data/app/com.Inlusion.Multiplayer-K9sNZgeAAVQqJ9t6tmzj6A==/lib/arm64, /data/app/com.Inlusion.Multiplayer-K9sNZgeAAVQqJ9t6tmzj6A==/base.apk!/lib/arm64-
v8a, /system/lib64, /system/product/lib64]]] couldn't find "liblibagora_segmentation_extension.so"
D/UE4     : [GameActivity] Failed to load libagora_segmentation_extension library
D/UE4     : [GameActivity] java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.Inlusion.Multiplayer-K9sNZgeAAVQqJ9t6tmzj6A==/base.apk"],nativeLibraryDirectories=[/data/app/com.Inlusion.Multiplayer-K9sNZgeAAVQqJ9t6tmzj6A==/lib/arm64, /data/app/com.Inlusion.Multiplayer-K9sNZgeAAVQqJ9t6tmzj6A==/base.apk!/lib/arm64-
v8a, /system/lib64, /system/product/lib64]]] couldn't find "liblibagora_spatial_audio_extension.so"
D/UE4     : [GameActivity] Failed to load libagora_spatial_audio_extension library
D/UE4     : [GameActivity] java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.Inlusion.Multiplayer-K9sNZgeAAVQqJ9t6tmzj6A==/base.apk"],nativeLibraryDirectories=[/data/app/com.Inlusion.Multiplayer-K9sNZgeAAVQqJ9t6tmzj6A==/lib/arm64, /data/app/com.Inlusion.Multiplayer-K9sNZgeAAVQqJ9t6tmzj6A==/base.apk!/lib/arm64-
v8a, /system/lib64, /system/product/lib64]]] couldn't find "liblibagora_super_resolution_extension.so"
We need distribution builds in order to update them to the Oculus Store.

**Comment by oneSitDown** [comment]
it look like you do not import  agora **.so** library

**Comment by SarunasRamonas** [comment]
Thanks for the comment. Yes crash was because of ProGuard system.

Now I don't get those crashes, but errors are still there. And also it performs as expected (connects, voice chat is available).
