### ISSUE TITLE
ITMS-90482: Invalid Executable - The executable contains bitcode

### ISSUE THREAD

**Issue by joeholee** [AgoraIO-Extensions/Agora-Unreal-RTC-SDK#73]
Hello,

We have been using Agora SDK for screen share purposes.

We had no problem until now, but as Apple won't allow apps built with iOS SDK that is less than 16.1 from April, we had to go through some steps to build our app with Xcode 14.1, which uses the iOS 16.1 SDK.

Yet, when we are trying to deliver our app to the App Store, they tell us our app contains bitcode, which is also not going to be accepted from April.

We figured out that Agra frameworks for iOS contain bitcode.

We have tried some methods to disable bitcode from packaging, but it does not seem to work.

It would be very kind of you if you could give some suggestions on what to do.

![image](https://user-images.githubusercontent.com/84345021/228235963-ce08377f-d75a-4a1f-8f89-60be0fb3e0d4.png)

This is the message we received from Apple.

Any help would be deeply appreciated.

Best regards,

Joe

**Comment by joeholee** [comment]
Never mind.

Solved it by running bitcode_strip.

**Comment by saswat-mishra** [comment]
Where you run bitcode_strip? And did you have to run it on each zipped file or the unzipped ones in the engine folder?

Sorry I'm new to development on Mac and don't have much idea about this bit_code stuff.

**Comment by joeholee** [comment]
> Where you run bitcode_strip? And did you have to run it on each zipped file or the unzipped ones in the engine folder?
> 
> Sorry I'm new to development on Mac and don't have much idea about this bit_code stuff.

Since I am not working for the same company I'm sorry I cannot correctly elaborate on the solution.

Yet, as I recall I had to unzip and run the bitcode_strip command for each file and zipped them.

I think you could google about how to run the bitcode_strip command because I also knew nothing about those issues when I had to manage them. I wasn't even a sw engineer so I think you could cope with the problem easier than me.

Sorry for the late reply.
