### ISSUE TITLE
Paths

### ISSUE THREAD

**Issue by h2ogit** [AgoraIO-Extensions/Agora-Unreal-RTC-SDK#76]
some files have include folder in lower case, others in upper case, but folder is in lower case.

**Comment by h2ogit** [comment]
besides that it has tons of warnings like

**Comment by oneSitDown** [comment]
I think this is a warning，if you want to fix this problem，you can fix by yourself.

**Comment by WinterPu** [comment]
This will be fixed in the next version, the issue will be closed when the new one has been released.
