### ISSUE TITLE
How to avoid echoing game sounds when joining a screen sharing channel with enabled LoopbackRecording ?

### ISSUE THREAD

**Issue by playamigos** [AgoraIO-Extensions/Agora-Unreal-RTC-SDK#79]
The issue is when I screen share with audio enable (by enabling EnableLoopBackRecording), all game sounds are being echoed on all the listeners. This is because EnableLoopbackRecording just publishes the audio from selected sound card, which includes all the sounds inside the game itself.

Is there some way to exclude the Game's Self Audio from being publishing to the channel while using audio with screen share? EnableLoopBackRecording seems useless without the option to exclude game audio. or is there any other way to transmit audio during screen share?

**Comment by WinterPu** [comment]
Hi, I would like to confirm, when you share the screen, do you want only the microphone audio to be published, or except for the game sounds, do you also want other loopback audio to be published (like music you play). If it is the former, you can just set **publishMicrophoneTrack** to be true in **ChannelMediaOptions**.  Also, please let me know which platform you are targeting for.

**Comment by playamigos** [comment]
I am targeting Windows platform only for now.

I don't want microphone volume to be published. I need only Screen share with system/application sounds to be published
I don't want game(in which agora is embedded) sounds to be published during a full screen share, but other open application sounds can be published like songs in background, YouTube video playing in browser etc.

Currently when using EnableLoopBackRecording, it publishes every sound my sound card captures including in-game sounds. which causing duplication or echo of game sounds for all audience in the screen share channel. I just want to avoid this echo from happening.

**Comment by icywind** [comment]
Hi @playamigos, the current Unreal SDK version does not support feature like this.  We are aware of the demand for such feature and working on an implementation right now. Please stay tuned for the next release coming in August.

**Comment by playamigos** [comment]
Awesome, waiting for the next release. Thanks for your effort in bringing this to unreal.

**Comment by WinterPu** [comment]
It should be supported. For any other questions, you can contact [Agora Support](https://www.agora.io/en/customer-support/).
