### ISSUE TITLE
How can I stop billing for audio minutes ?

### ISSUE THREAD

**Issue by playamigos** [AgoraIO-Extensions/Agora-Unreal-RTC-SDK#80]
Currently I am using Agora for just screen share without any kind of audio not even microphone.

I am not subscribing to any audio.
I am not publishing any audio.
I even disabled audio in blueprints, before configuring the channel join params.

But still I am getting billed for audio minutes. 
Is there some way where we can listen to user joining events in a channel without getting billed for audio?

**Comment by icywind** [comment]
Hi @playamigos , if you disabled audio, then what you getting billed for is probably for the screensharing feature.  That feature does incur minimum charge for the bandwidth, which fits into the audio minutes (much lower than video minuites).

**Comment by playamigos** [comment]
I am actually using a proxy user who connect to the channel with audio and video disabled and doesn't publish or subscribe to audio. when this user finds a new user with a name containing keyword "broadcast", he then joins the channel himself as an audience by subscribing to the video.

So I think, I am getting billed for Proxy user who didn't subscribe to audio or video but just there to listen for user joining events.

My billed audio minutes are roughly around - 4000 mins whereas video minutes are just at 50 mins 

This is my proxy user configuration:
![image](https://github.com/AgoraIO-Extensions/Agora-Unreal-RTC-SDK/assets/14229723/54df1725-ae7a-47c9-975c-d3aadf47091f)

**Comment by playamigos** [comment]
also adding my audience and broadcaster channel config:

Here is broadcaster channel config
![image](https://github.com/AgoraIO-Extensions/Agora-Unreal-RTC-SDK/assets/14229723/59d7601b-d1fd-4a74-8d1d-9fa76798fabb)

Here is audience channel config
![image](https://github.com/AgoraIO-Extensions/Agora-Unreal-RTC-SDK/assets/14229723/16f7bd2f-c65a-44fe-a7f1-1dd44e1c12a4)


I don't understand why I am getting billed for audio with not even a single user subscribed/published to the Audio.

**Comment by WinterPu** [comment]
You will be charged when you successfully join the channel. Please note that there is a free quota of 10,000 minutes per month. If you want a more flexible billing plan, please contact sales.  https://www.agora.io/en/talk-to-us/
