### ISSUE TITLE
Windows 11 display

### ISSUE THREAD

**Issue by Shumaro211** [AgoraIO-Extensions/Agora-Unreal-RTC-SDK#87]
Hello again, I got a problem, someone reported us that his windows 11 machine only shows on the screen share system "display 1", but getting more than one, so at least the name of each display is not set correctly.

We suspect is because of Windows 11, are you aware of that problem? I'll try to get a windows 11 computer to see if the problem persist. 

Thank you!

**Comment by WinterPu** [comment]
Sry, I don't get it. Can you explain the issue with more details? What does he expect to see, 1 view or 2 more views? Both views are with the name "Display 1"? 

BTW, I am using Win11. If the problem is as I understood it, then I haven't encountered it before.

**Comment by Shumaro211** [comment]
Instead of showing displays like the applications you have
![Screenshot_20230827_222314_WhatsApp](https://github.com/AgoraIO-Extensions/Agora-Unreal-RTC-SDK/assets/66711189/884aa7ec-4245-44df-9bbc-a4187143eac6)
opened it just shows display1

**Comment by WinterPu** [comment]
I believe the issue might be that the source infos hasn't been accurately copied. 
You can verify by checking the example provided below.  ( currently, recommend use UE4.27)
https://github.com/AgoraIO-Extensions/Agora-Unreal-RTC-SDK/tree/main/Agora-Unreal-SDK-CPP-Example/Source/AgoraExample/Examples/Advanced/ScreenShare

The picture below shows the result of running it on Windows 11.
![image](https://github.com/AgoraIO-Extensions/Agora-Unreal-RTC-SDK/assets/12077942/169d12d8-482b-49a4-ae9c-c555f526aaaa)

**Comment by Shumaro211** [comment]
Oh is working correclty in our computers; we discarted using windows 11 for some problems with our login system, so the OS is the only clue for the problem he sended us.

I suppose is not something about a value that changed in windows 11 because of what you are sending, we are using UE5.0.3, I guess is something else.
