### ISSUE TITLE
How to use computer's audio

### ISSUE THREAD

**Issue by Shumaro211** [AgoraIO-Extensions/Agora-Unreal-RTC-SDK#88]
I wanna use the computer's audio, I've seen that I can use the function **enableLoopbackRecordingex**.

I see I can get the RtcConnection& connection from the AgoraVideoWidget class, but how can I get the "deviceName" parameter in the AgoraVideoWidget class?
![image](https://github.com/AgoraIO-Extensions/Agora-Unreal-RTC-SDK/assets/66711189/c70bf00b-f50f-470f-b1fe-c5a42c49017d)

Do I need to get the "deviceName" from the Device Manager class using the GetAudioPlaybackDevice() function? this is what I mean.
![image](https://github.com/AgoraIO-Extensions/Agora-Unreal-RTC-SDK/assets/66711189/2dbdde54-deb1-40ee-a52d-74e76fc9ae9d)

And is it possible to share the computer's audio without sharing the microphone's audio?
I had to disable the microphone's audio so my screen only shares video because of how I had to set up the audio behavior in our virtual world.

**Comment by WinterPu** [comment]
1. For the first one, yes, please refer to enableLoopbackRecordingex (if you are using "connection" to manage your channels) for Windows / Mac. It is almost what you showed here.
2. You can refere to device manager examaple here:
https://github.com/AgoraIO-Extensions/Agora-Unreal-RTC-SDK/tree/main/Agora-Unreal-SDK-CPP-Example/Source/AgoraExample/Examples/Advanced/DeviceManager 
but it doesn't support on mobile platform.
On Mobile Platform, you can just use ChannelMediaOptions:
	ChannelMediaOptions.publishScreenCaptureVideo = true
	ChannelMediaOptions.publishScreenCaptureAudio = true
3. For the last question, you can set ChannelMediaOptions.publishMicrophoneTrack to false to see if it meets your needs.
    You can also mute it using muteRecordingSignal

**Comment by Shumaro211** [comment]
I included the new code for the screen share classes and the utility folder, I changed the build.cs to include the extra modules such as Json and JsonUtilities, now I'm getting 33 errors like these:

![image](https://github.com/AgoraIO-Extensions/Agora-Unreal-RTC-SDK/assets/66711189/b61acadf-9222-44ec-9d1f-14ff6e8acf93)
45>BFL_HTTPHelper.cpp.obj : error LNK2001: unresolved external symbol "public: virtual bool cdecl FJsonValueNumberString::TryGetString(class FString &)const " (?TryGetString@FJsonValueNumberString@@UEBA_NAEAVFString@@@Z)
45>BFL_HTTPHelper.cpp.obj : error LNK2001: unresolved external symbol "public: virtual bool cdecl FJsonValueString::TryGetString(class FString &)const " (?TryGetString@FJsonValueString@@UEBA_NAEAVFString@@@Z)

Is it a module missing? now I added System.IO; using System; to the build.cs and got 75 errors
