### ISSUE TITLE
Disable screen share when joining/leaving

### ISSUE THREAD

**Issue by Shumaro211** [AgoraIO-Extensions/Agora-Unreal-RTC-SDK#89]
Hello and thank you so much for helping!, I could share my computer's audio without my mic.

But now I notice that when someone joins and leaves while sharing, the video widget stops or freeze and I need to stop sharing and share again to fix it.

I can code something to share again, but is it normal? I guess is related to the AgoraVideoWidget class, because there is only one client using the ScreenShareVideo.

Is there something you think I can check to make sure the clients are not running something that might interfer with the connection?
I just run the project in the editor to share the video and in a build in another computer to make sure is not related to a replication problem running code in the machine is sharing.

**Comment by WinterPu** [comment]
1. 【When someone joins and leaves】: you can check what you did in the **onUserJoined** or **onUserOffline** functions. I ran the examples with UE4.27, and the Video Widget won't freeze.
2. You can check the example link here: [https://github.com/AgoraIO-Extensions/Agora-Unreal-RTC-SDK/tree/main/Agora-Unreal-SDK-CPP-Example/Source/AgoraExample/Examples/Advanced/ScreenShare ↗](https://github.com/AgoraIO-Extensions/Agora-Unreal-RTC-SDK/tree/main/Agora-Unreal-SDK-CPP-Example/Source/AgoraExample/Examples/Advanced/ScreenShare)
3. Make sure you use the right frame, you could check **onCaptureVideoFrame** in VideoObserverInternal.h to debug

**Comment by Shumaro211** [comment]
well I don't have those funtions, I'm using a version from the beggining of this year: 
![image](https://github.com/AgoraIO-Extensions/Agora-Unreal-RTC-SDK/assets/66711189/5ed319cb-f6b3-4afc-b99e-13e04641fb8c)
These are the functions I have, I hope to be able to replace the code without any problems, and that can solve my problem.

**Comment by Shumaro211** [comment]
I added the new code for the screen share classes, so I had to add the utility folder, I added the modules that I found in the example project for the uproject and build.cs such as Json and JsonUtilities.

But now I'm getting 77 errors like this one: 45>BFL_HTTPHelper.cpp.obj : error LNK2001: unresolved external symbol "public: virtual bool cdecl FJsonValueString::TryGetString(class FString &)const " (?TryGetString@FJsonValueString@@UEBA_NAEAVFString@@@Z)
![image](https://github.com/AgoraIO-Extensions/Agora-Unreal-RTC-SDK/assets/66711189/206fa573-2417-4c0a-828f-4e8cfbf0f021)

**Comment by Shumaro211** [comment]
I deleted all the utility references and files, now I got this error: 

`Error    LNK2019    unresolved external symbol "declspec(dllimport) class agora::rtc::IRtcEngineEx * cdecl agora::rtc::ue::createAgoraRtcEngineEx(void)" (imp_?createAgoraRtcEngineEx@ue@rtc@agora@@YAPEAVIRtcEngineEx@23@XZ) referenced in function "protected: void cdecl UScreenShareWidget::InitAgoraEngine(class FString,class FString,class FString)" (?InitAgoraEngine@UScreenShareWidget@@IEAAXVFString@@00@Z)    OriginWorlds    E:\Workspaces\UE_Source\Engine\Intermediate\ProjectFiles\ScreenShareWidget.cpp.obj`

So let me just ask, I see you added lots of stuff in every function and those two that you told me: onUserJoined and onUserOffline, I would not think that my older version is the problem unless you changed something in the agora's backend maybe.

If you think it was the problem, I just need to solve those errors.

**Comment by WinterPu** [comment]
Let's solve this one by one. Firstly, it's better to compile the project with UE4.27 for now. The shader-related case is currently not compatible with UE5. Secondly, you can try to find the agorasdk.log file at the following path: C:\Users\admin\AppData\Local\Agora\UE4Editor-Win64-DebugGame.

**Comment by Shumaro211** [comment]
Well using the 4.27 is something else that would destroy the project. It was working with the old code, are those problems related to something new? or is it possible to disable something? I just need the audio, screen share and video widget functionalities, nothing else.

I have many folders in that path with older dates, I'm gonna run everything to see if a new log is created.
