### ISSUE TITLE
Crashing when playing and build

### ISSUE THREAD

**Issue by Shumaro211** [AgoraIO-Extensions/Agora-Unreal-RTC-SDK#91]
I commented this in another Issue.

I just compiled the 5.0.3 version from source (but I also tried with the marketplace version) and downloaded the latest files, and the engine is crashin every time I press any of the buttons of the multiple features, when the App id is valid, I did not put a token, not sure if it might be a problem.

![image](https://github.com/AgoraIO-Extensions/Agora-Unreal-RTC-SDK/assets/66711189/83a7a096-e431-4c7e-b7fe-4d53b9f66bd1)
All I get is this for the ScreenShareWhileVideoCall is this line: RtcEngineProxy->stopScreenCapture();
But I get it even from the device manager class

**Comment by WinterPu** [comment]
You can attach the log file to provide more details. Additionally, you can simply use the marketplace version, as it does not require a source build engine version.

**Comment by Shumaro211** [comment]
I can't use the marketplace version because I need to compile a server build, but tried with both. This is the log:
[AgoraExample.log](https://github.com/AgoraIO-Extensions/Agora-Unreal-RTC-SDK/files/12554925/AgoraExample.log)

So is crashing in your example project and my own project, after I updated the code.
But well thanks in advance!

**Comment by WinterPu** [comment]
Did you call **InitAgoraEngine** before joining the channel (OnBtnJoinChannelClicked)?

**Comment by WinterPu** [comment]
1. Could you share what you do in **InitAgoraWidget** & **OnJoinButtonClick** ?
2. Also In **Initialize** or **InitializeEx**, it would return the result code. You could check if it returns 0.
<img width="194" alt="image" src="https://github.com/AgoraIO-Extensions/Agora-Unreal-RTC-SDK/assets/12077942/319cc19a-e639-4572-8883-62e27582d64c">
