### ISSUE TITLE
BP Project unable to launching scenes in Windows packaged builds

### ISSUE THREAD

**Issue by chakradhar-xr** [AgoraIO-Extensions/Agora-Unreal-RTC-SDK#92]
I have downloaded the Blueprint Only project and entered the appid, ChannelName, Token and everything works fine in Editor. But when I packaged the Main_Level for Windows, app is unable to launch any of Audio,Video,ScreenShare scene

**Comment by WinterPu** [comment]
Did you modify the cook settings and miss out on the other maps?

**Comment by WinterPu** [comment]
You could type 'open [MapName]' in the UE console to see if it works.

**Comment by icywind** [comment]
Since we could not reproduce this issue and not hear back from you, we assume this has been assume. Please reopen it if you find it otherwise with the latest SDK. Thank you!
