### ISSUE TITLE
How does one mute users with options (using the BP variant)

### ISSUE THREAD

**Issue by HereafterMills** [AgoraIO-Extensions/Agora-Unreal-RTC-SDK#94]
Hi, 
Im trying to find features such as 
Local Mute: Mute a user only for me
Global Mute: Mute a user for everyone
Turn all other publish states off: Turn the mic of all remote users off. 

Is there a facility to do this with Agora?

**Comment by WinterPu** [comment]
1. You could refer to the API **muteRemoteAudioStream** / **muteAllRemoteAudioStreams**.
2. 【2,3】Currently, the **RTC** SDK does not have the capability to provide an administrative function for muting someone for others.

Ref: https://docs.agora.io/en/3.x/voice-calling/best-practices/set-subscribing-state?platform=android

**Comment by HereafterMills** [comment]
Fair enough. although, wouldnt setting a user as an 'Audience' instead of 'Broadcaster' achieve this to mute a user for all other users? Im yet to test this, but thats what i did. The use case here is if a teacher wants to mute all the kids in class, and then unmute one by one based on who should be talking

For local mute, im simply using the blocklist. An admin can also  do this for someone else by sending an RPC call within unreal to their client and the client performs the task from its local UID. 

Thanks though

**Comment by WinterPu** [comment]
For an RTC SDK, it lacks the ability to notify other students when the teacher mutes a specific student. One possible solution would be to use an additional server to send this message. Alternatively, we do have an RTM SDK that can perform this function, but currently, it does not have an Unreal version.
