### ISSUE TITLE
Indentation error on android

### ISSUE THREAD

**Issue by HereafterMills** [AgoraIO-Extensions/Agora-Unreal-RTC-SDK#96]
Seems to be an indentation error in AgoraIRtcEngineEventHandler.cpp.

/AgoraPlugin/Source/AgoraPlugin/Private/AgoraBluePrintPlugin/AgoraIRtcEngineEventHandler.cpp(1530,4): error: misleading indentation; statement is not part of the previous 'if' [-Werror,-Wmisleading-indentation]

Trying a build after fixing it. Will report back.

Error pops up only when building for Android for me, Windows works fine.

**Comment by WinterPu** [comment]
This issue will be fixed in the upcoming release version. You can early-access it in the dev/4.2.1 branch, or you can manually format the code yourself.

**Comment by HereafterMills** [comment]
Thanks man. You're awesome
