### ISSUE TITLE
Interactive Whiteboard

### ISSUE THREAD

**Issue by HereafterMills** [AgoraIO-Extensions/Agora-Unreal-RTC-SDK#97]
Hi @WinterPu 

Just wanted to check. Does this currently work in the plugin, and if not, is there any reason for it or has it simply not been implemented yet?

Im trying to work out if with some effort i could get my guys to implement it if not already working.

**Comment by WinterPu** [comment]
That's still in dev.

**Comment by HereafterMills** [comment]
Good to hear. Is there any particular issue you are facing? Something that might be a showstopper? Im aware of how hard it can be for unreal to replicate 2d textures across servers. Been trying to make my own whiteboard on unreal for a while.

**Comment by WinterPu** [comment]
Our native dev team is still working on it, therefore, for now, I have no suggestions on whiteboard development.

**Comment by HereafterMills** [comment]
Ok. Thanks
