### ISSUE TITLE
Strange crash in project (Not urgent)

### ISSUE THREAD

**Issue by HereafterMills** [AgoraIO-Extensions/Agora-Unreal-RTC-SDK#98]
Hi, 

So everything works well within my test project. But when i move it over to my main project, i get a few crashes in the editor. 

In suspecting this has something to do with a race condition. The crashes happen about 10 seconds after i end play in editor mode. 

On debugging, here is where it crashes:
I keep continuing to get the next few images.

A breakpoint instruction (__debugbreak() statement or a similar call) was executed in UnrealEditor.exe.
Exception thrown at 0x00007FF89C019FF3 (UnrealEditor-Core.dll) in UnrealEditor.exe: 0xC0000005: Access violation reading location 0x0000000000000001.

![image](https://github.com/AgoraIO-Extensions/Agora-Unreal-RTC-SDK/assets/37168482/06180455-b232-4388-b0ab-df6007ac0d5c)

![image](https://github.com/AgoraIO-Extensions/Agora-Unreal-RTC-SDK/assets/37168482/371f1a58-5484-499a-9c15-e5457da77225)

![image](https://github.com/AgoraIO-Extensions/Agora-Unreal-RTC-SDK/assets/37168482/ef3821ce-24b4-4366-947e-85b9d54aeef5)

And then keeps cycling in the same area - 
![image](https://github.com/AgoraIO-Extensions/Agora-Unreal-RTC-SDK/assets/37168482/be9609da-c285-4308-a801-3a8b5281bf38)

'''Exception thrown at 0x00007FF89C019FF3 (UnrealEditor-Core.dll) in UnrealEditor.exe: 0xC0000005: Access violation reading location 0x0000000000000001.
Unhandled exception at 0x00007FF89C019FF3 (UnrealEditor-Core.dll) in UnrealEditor.exe: 0xC0000005: Access violation reading location 0x0000000000000001.
Exception thrown at 0x00007FF89C019FF3 (UnrealEditor-Core.dll) in UnrealEditor.exe: 0xC0000005: Access violation reading location 0x0000000000000001.
Unhandled exception at 0x00007FF89C019FF3 (UnrealEditor-Core.dll) in UnrealEditor.exe: 0xC0000005: Access violation reading location 0x0000000000000001.
Exception thrown at 0x00007FF89C019FF3 (UnrealEditor-Core.dll) in UnrealEditor.exe: 0xC0000005: Access violation reading location 0x0000000000000001.
Unhandled exception at 0x00007FF89C019FF3 (UnrealEditor-Core.dll) in UnrealEditor.exe: 0xC0000005: Access violation reading location 0x0000000000000001.
Exception thrown at 0x00007FF89C019FF3 (UnrealEditor-Core.dll) in UnrealEditor.exe: 0xC0000005: Access violation reading location 0x0000000000000001.
Unhandled exception at 0x00007FF89C019FF3 (UnrealEditor-Core.dll) in UnrealEditor.exe: 0xC0000005: Access violation reading location 0x0000000000000001.
Exception thrown at 0x00007FF89C019FF3 (UnrealEditor-Core.dll) in UnrealEditor.exe: 0xC0000005: Access violation reading location 0x0000000000000001.
Unhandled exception at 0x00007FF89C019FF3 (UnrealEditor-Core.dll) in UnrealEditor.exe: 0xC0000005: Access violation reading location 0x0000000000000001.
Exception thrown at 0x00007FF89C019FF3 (UnrealEditor-Core.dll) in UnrealEditor.exe: 0xC0000005: Access violation reading location 0x0000000000000001.
'''

This is after pressing continue a bunch of times.

**Comment by WinterPu** [comment]
Could you offer logs for more details? Any clues in the Call Stack?

**Comment by icywind** [comment]
@HereafterMills , we want to check if this issue has been resolved.  Did you find the cause from the log file? Another hint from a common pitfall is that the Agora engine did not get properly disposed when the game stop playing.  That would cause similar crashing issue in the Editor like you experience.

**Comment by HereafterMills** [comment]
This still happens for me in my project but not in the example template. @icywind 

You're probably correct about the cause, bit I'm not sure how to resolve it.

Fir now, iv disabled voice in the editor

**Comment by HereafterMills** [comment]
@WinterPu Was trying to get the logs, but unreal doesnt write anything in the logs. Which is why i had to run it in debug mode to get the call stack

**Comment by icywind** [comment]
> This still happens for me in my project but not in the example template. @icywind
> 
> You're probably correct about the cause, bit I'm not sure how to resolve it.
> 
> Fir now, iv disabled voice in the editor

Here are some code snippet copied from the examples:


```cpp
void UAgoraVideoWidget::UnInitAgoraEngine()
{
	if (RtcEngineProxy)
	{
		RtcEngineProxy->leaveChannel();
		RtcEngineProxy->unregisterEventHandler(UserRtcEventHandler.Get());
		RtcEngineProxy->release();
		RtcEngineProxy = nullptr;
		UBFL_Logger::Print(FString::Printf(TEXT("%s release agora engine"), *FString(FUNCTION_MACRO)), LogMsgViewPtr);
	}
}
```
Call this when quitting the app.  See if that works on your project?

**Comment by HereafterMills** [comment]
I'm using the blueprint example though. Should I create c++ class and try this?

**Comment by HereafterMills** [comment]
![image](https://github.com/AgoraIO-Extensions/Agora-Unreal-RTC-SDK/assets/37168482/701116ed-0121-41b5-acd1-008281a1836b)

This is what im currently doing. However, i am running this code in my game instance as follows:

![image](https://github.com/AgoraIO-Extensions/Agora-Unreal-RTC-SDK/assets/37168482/287e7d8f-21a0-437c-ae22-77a59811268a)
![image](https://github.com/AgoraIO-Extensions/Agora-Unreal-RTC-SDK/assets/37168482/cc57eac9-cdc9-4c5f-9055-94196dd0f465)

This is a platform game instance where onApplicationWillTerminate is called anyway at shutdown.
